<?php
/*********************/
/*                   */
/*  Version : 5.1.0  */
/*  Author  : RM     */
/*  Comment : 071223 */
/*                   */
/*********************/

define( "tribe_1", "Romans" );
define( "tribe_2", "Teutons" );
define( "tribe_3", "Gauls" );
define( "tribe_4", "Monsters" );
define( "tribe_5", "Tatar" );
define( "tribe_6", "Dboor" );
define( "tribe_7", "Arab" );
define( "item_1", "Woodcutter" );
define( "item_title_1", "Lumber" );
define( "item_curprod_1", "Current production" );
define( "item_nextprod_1", "Production at level" );
define( "item_unit_1", "per hour" );
define( "item_desc_1", "The woodcutter cuts trees to collect wood. The higher the woodcutter's level, the more wood is produced." );
define( "item_2", "Clay Pit" );
define( "item_title_2", "Clay" );
define( "item_curprod_2", item_curprod_1 );
define( "item_nextprod_2", item_nextprod_1 );
define( "item_unit_2", "per hour" );
define( "item_desc_2", "Clay is collected from clay pits. The higher the clay pit's level, the more clay is produced." );
define( "item_3", "Iron Mine" );
define( "item_title_3", "Iron" );
define( "item_curprod_3", item_curprod_1 );
define( "item_nextprod_3", item_nextprod_1 );
define( "item_unit_3", "per hour" );
define( "item_desc_3", "Iron is mined from these mines. The higher the level, the greater the iron production." );
define( "item_4", "Wheat Field" );
define( "item_title_4", "Wheat" );
define( "item_curprod_4", item_curprod_1 );
define( "item_nextprod_4", item_nextprod_1 );
define( "item_unit_4", "per hour" );
define( "item_desc_4", "The population's food is grown in the wheat fields. The higher the wheat field's level, the more wheat is produced." );
define( "item_5", "Sawmill" );
define( "item_title_5", item_5 );
define( "item_curprod_5", "Current construction time" );
define( "item_nextprod_5", "Construction time at level" );
define( "item_unit_5", "%" );
define( "item_desc_5", "The wood collected by a woodcutter is turned into boards in the sawmill. Every level raises the wood production up to a maximum of 25 percent." );
define( "item_6", "Brickworks" );
define( "item_title_6", item_6 );
define( "item_curprod_6", item_curprod_5 );
define( "item_nextprod_6", item_nextprod_5 );
define( "item_unit_6", item_unit_5 );
define( "item_desc_6", "Clay is turned into bricks in the brickworks. Every level raises clay production up to a maximum of 25 percent." );
define( "item_7", "Iron Foundry" );
define( "item_title_7", item_7 );
define( "item_curprod_7", item_curprod_5 );
define( "item_nextprod_7", item_nextprod_5 );
define( "item_unit_7", item_unit_5 );
define( "item_desc_7", "Iron is smelted in the iron foundry. Every level raises iron production up to a maximum of 25 percent." );
define( "item_8", "Flour Mill" );
define( "item_title_8", item_8 );
define( "item_curprod_8", item_curprod_5 );
define( "item_nextprod_8", item_nextprod_5 );
define( "item_unit_8", item_unit_5 );
define( "item_desc_8", "Wheat is ground into flour at the flour mill. Every level increases wheat production up to a maximum of 25 percent." );
define( "item_9", "Bakery" );
define( "item_title_9", item_9 );
define( "item_curprod_9", item_curprod_5 );
define( "item_nextprod_9", item_nextprod_5 );
define( "item_unit_9", item_unit_5 );
define( "item_desc_9", "Flour from the mill is baked into bread at the bakery. In conjunction with the flour mill, wheat production can be increased by up to 50 percent." );
define( "item_10", "Warehouse" );
define( "item_title_10", item_10 );
define( "item_curprod_10", "Current storage capacity" );
define( "item_nextprod_10", "Storage capacity at level" );
define( "item_unit_10", "Resource units" );
define( "item_desc_10", "Wood, clay, and iron are stored in the warehouse. The higher its level, the more resources can be stored. At level 20, it is possible to build additional warehouses." );
define( "item_11", "Granary" );
define( "item_title_11", item_11 );
define( "item_curprod_11", "Current storage capacity" );
define( "item_nextprod_11", "Storage capacity at level" );
define( "item_unit_11", "Units of wheat" );
define( "item_desc_11", "The wheat from the wheat fields is stored in the granary. The higher its level, the more wheat can be stored. At level 20, it is possible to build additional granaries." );
define( "item_12", "Blacksmith" );
define( "item_title_12", item_12 );
define( "item_curprod_12", "Current force of arms" );
define( "item_nextprod_12", "Force of Arms at level" );
define( "item_unit_12", "%" );
define( "item_desc_12", "Your warriors' weapons are improved in the forges of the blacksmith. The higher the level, the greater the possibilities for weapon improvement." );
define( "item_13", "Armory" );
define( "item_title_13", item_13 );
define( "item_curprod_13", "Force current armor " );
define( "item_nextprod_13", "Force current armor at level" );
define( "item_unit_13", "%" );
define( "item_desc_13", "Your soldiers' armor is improved in the forges of the armory. The higher the level, the greater the number of possibilities for armor upgrades." );
define( "item_14", "Tournament Square" );
define( "item_title_14", item_14 );
define( "item_curprod_14", "Current speed movement of troops" );
define( "item_nextprod_14", "Speed movement of troops at level" );
define( "item_unit_14", "%" );
define( "item_desc_14", "At the tournament square, your troops can improve their stamina. The higher the level, the faster your troops will move when further than 30 fields away." );
define( "item_15", "Main Building" );
define( "item_title_15", item_15 );
define( "item_curprod_15", "Current construction time" );
define( "item_nextprod_15", "Construction time at level" );
define( "item_unit_15", "%" );
define( "item_desc_15", "The architects of the village live in the ".item_15." building.<br> The higher the level, the faster other buildings will be built or upgraded." );
define( "item_16", "Rally Point" );
define( "item_title_16", item_16 );
define( "item_curprod_16", "" );
define( "item_nextprod_16", "" );
define( "item_unit_16", "" );
define( "item_desc_16", "The village's troops meet at the rally point. From here you can send them out to reinforce, raid, or conquer another village.

The rally point can only be built at the rally point spot, which is the crescent-shaped piece of grass to the right of the village center." );
define( "item_17", "Marketplace" );
define( "item_title_17", item_17 );
define( "item_curprod_17", "" );
define( "item_nextprod_17", "" );
define( "item_unit_17", "" );
define( "item_desc_17", "You can trade resources with other players via the marketplace. The higher the level, the more merchants are available." );
define( "item_18", "Embassy" );
define( "item_title_18", item_18 );
define( "item_curprod_18", "" );
define( "item_nextprod_18", "" );
define( "item_unit_18", "" );
define( "item_desc_18", "The embassy is the office for the diplomats. At level 1, you can join an alliance. At level 3, you can form your own alliance.

Every level of the embassy raises the maximum number of alliance members by 3 until level 20, when there may be a maximum of 60 alliance members." );
define( "item_19", "Barracks" );
define( "item_title_19", item_19 );
define( "item_curprod_19", "" );
define( "item_nextprod_19", "" );
define( "item_unit_19", "" );
define( "item_desc_19", "All foot soldiers are trained in the barracks. The higher the level of the barracks, the faster the troops are trained." );
define( "item_20", "Stable" );
define( "item_title_20", item_20 );
define( "item_curprod_20", "" );
define( "item_nextprod_20", "" );
define( "item_unit_20", "" );
define( "item_desc_20", "All mounted troops are trained in the stable. The higher the level, the faster the troops are trained." );
define( "item_21", "Siege Workshop" );
define( "item_title_21", item_21 );
define( "item_curprod_21", "" );
define( "item_nextprod_21", "" );
define( "item_unit_21", "" );
define( "item_desc_21", "Siege weapons such as catapults and rams are produced in the siege workshop. The higher the level, the faster the units are produced." );
define( "item_22", "Academy" );
define( "item_title_22", item_22 );
define( "item_curprod_22", "" );
define( "item_nextprod_22", "" );
define( "item_unit_22", "" );
define( "item_desc_22", "New troop types can be researched at the academy. The higher the level, the greater the number of troop types available to be researched." );
define( "item_23", "Cranny" );
define( "item_title_23", item_23 );
define( "item_curprod_23", "Currently hidden" );
define( "item_nextprod_23", "Amount hidden at level" );
define( "item_unit_23", "units" );
define( "item_desc_23", "In the event of an attack on your village, a portion of the resources in the warehouse can be hidden in the cranny. These resources can not be taken by the attackers.

At level 1, the cranny hides 100 units of each resource. The Teutons have a raiding bonus and the cranny hides only 4/5 of its resources against them. The Gauls have a cranny bonus and hide twice as many resources in their crannies." );
define( "item_24", "Town Hall" );
define( "item_title_24", item_24 );
define( "item_curprod_24", "" );
define( "item_nextprod_24", "" );
define( "item_unit_24", "" );
define( "item_desc_24", "You can host extravagant parties for your citizens at the town hall. Such parties increase your number of culture points. Each party grants you a flat sum of culture points after the party has ended.

Culture points are needed to found or conquer new villages." );
define( "item_25", "Residence" );
define( "item_title_25", item_25 );
define( "item_curprod_25", "Currently largest number" );
define( "item_nextprod_25", "Largest number at level" );
define( "item_unit_25", "Village" );
define( "item_desc_25", "The residence is a small palace that the king lives in when he visits the village. The residence protects the village from being conquered by enemies. A residence and palace may not be built in the same village." );
define( "item_26", "Palace" );
define( "item_title_26", item_26 );
define( "item_curprod_26", "" );
define( "item_nextprod_26", "" );
define( "item_unit_26", "" );
define( "item_desc_26", "The nation's king lives in the palace. A village which has a palace can be named the capital. A capital cannot be conquered. A palace and residence may not be built in the same village. Only one palace is allowed per account.

A stonemason and fields higher than level 10 can only be built in the capital" );
define( "item_28", "Trade Office" );
define( "item_title_28", item_28 );
define( "item_curprod_28", "Current capacity absorptive" );
define( "item_nextprod_28", "capacity absorptive at level" );
define( "item_unit_28", "Resources" );
define( "item_desc_28", "The trade carts of your marketplace can be improved in the trade office. The higher the level, the more each merchant can carry." );
define( "item_29", "Great Barracks" );
define( "item_title_29", item_29 );
define( "item_curprod_29", "" );
define( "item_nextprod_29", "" );
define( "item_unit_29", "" );
define( "item_desc_29", "The great barracks allows the training of additional troops. The troops cost three times as much, however. In conjunction with the normal barracks, twice as many troops can be built in the same amount of time." );
define( "item_30", "Great Stable" );
define( "item_title_30", item_30 );
define( "item_curprod_30", "" );
define( "item_nextprod_30", "" );
define( "item_unit_30", "" );
define( "item_desc_30", "The great stable allows the training of additional cavalry. These troops cost three times as much, however." );
define( "item_31", "Earth Wall" );
define( "item_title_31", "Earth Wall" );
define( "item_curprod_31", "Defense Bonus now" );
define( "item_nextprod_31", "Defense Bonus at level" );
define( "item_unit_31", "%" );
define( "item_desc_31", "The earth wall protects your village from attacks. The higher the level, the easier it will be for your defenders to successfully fight off the pillaging hordes of your enemies." );
define( "item_32", item_31 );
define( "item_title_32", item_31 );
define( "item_curprod_32", item_curprod_31 );
define( "item_nextprod_32", item_nextprod_31 );
define( "item_unit_32", item_unit_31 );
define( "item_desc_32", item_desc_31 );
define( "item_33", item_31 );
define( "item_title_33", item_31 );
define( "item_curprod_33", item_curprod_31 );
define( "item_nextprod_33", item_nextprod_31 );
define( "item_unit_33", item_unit_31 );
define( "item_desc_33", item_desc_31 );
define( "item_34", "Stonemason" );
define( "item_title_34", item_34 );
define( "item_curprod_34", "Current stability" );
define( "item_nextprod_34", "stability at level" );
define( "item_unit_34", "%" );
define( "item_desc_34", "The stonemason is an expert at manipulating stone. The higher the level, the stronger each of the buildings in your village will be.

The stonemason can only be built in the capital." );
define( "item_35", "Brewery" );
define( "item_title_35", item_34 );
define( "item_curprod_35", "Current stability" );
define( "item_nextprod_35", "Stability at level" );
define( "item_unit_35", "%" );
define( "item_desc_35", "Tasty mead is brewed in the brewery and later quaffed by the soldiers during the celebrations. 

 These drinks make your soldiers braver and stronger in battles (1% per level). Unfortunately the chiefs’ power of persuasion is decreased and catapults can only do random hits. 

 It can only be built by Teutons and only in their capital. It affects the whole empire. " );
define( "item_36", "Trapper" );
define( "item_title_36", item_36 );
define( "item_curprod_36", "Currently largest number" );
define( "item_nextprod_36", "Largest number at level" );
define( "item_unit_36", "Trap" );
define( "item_desc_36", "The trapper protects your village with well hidden traps. This means that unwary enemies can be imprisoned and wont be able to harm your village anymore.
Troops cannot be freed with a raid. When the troops get freed with a successful normal attack, 1/3 of the traps are automatically repaired. If the owner of the traps release the captives all of the traps can be repaired. 

 Note that this building can only be constructed by Gauls." );
define( "item_36_t1", "You currently have <b>%s</b> of the traps and <b>%s</b> where the prisoners." );
define( "item_36_t2", "" );
define( "item_36_t3", "" );
define( "item_37", "Heros Mansion" );
define( "item_title_37", item_37 );
define( "item_curprod_37", "Currently largest number" );
define( "item_nextprod_37", "Largest number at level" );
define( "item_unit_37", "Oasis" );
define( "item_desc_37", "In the hero's mansion you can train a hero. A normal unit is required to be trained into a hero. A barracks or stable is also necessary to train a hero.

 At levels 10, 15, and 20 your hero can annex 1, 2, and 3 oases, respectively. These oases increase production of their particular resource in the annexing village." );
define( "item_38", "Great Warehouse" );
define( "item_title_38", item_38 );
define( "item_curprod_38", "Current storage capacity" );
define( "item_nextprod_38", "Storage capacity at level" );
define( "item_unit_38", "Resources" );
define( "item_desc_38", "In your Warehouse, the resources wood, clay and iron are stored. The Great Warehouse offers you more space than the regular warehouse to keep your resources safe and dry." );
define( "item_39", "Great Granary" );
define( "item_title_39", item_39 );
define( "item_curprod_39", "Current storage capacity" );
define( "item_nextprod_39", "Storage capacity at level" );
define( "item_unit_39", "wheat" );
define( "item_desc_39", "In the Granary, the wheat produced by your wheat fields is stored. The Great Granary offers you more space than the regular Granary to keep your crops safe and dry." );
define( "item_40", "World Wonder" );
define( "item_title_40", item_40 );
define( "item_curprod_40", "Current level" );
define( "item_nextprod_40", "Next Level" );
define( "item_unit_40", "" );
define( "item_desc_40", "The Wonder Of The World represents the pride of creation. Only the mightiest and richest are able to build such a masterwork and defend it against envious enemies." );
define( "item_41", "Horse Drinking Pool" );
define( "item_title_41", item_41 );
define( "item_curprod_41", "Current speed Training Knights" );
define( "item_nextprod_41", "Speed Training Knights at level" );
define( "item_unit_41", "%" );
define( "item_desc_41", "Your Cavalry benefit from much improved health with the Horse Drinking Pool and with that comes an increase in the speed of their training by 1% per level.

The horse drinking pool reduces the Crop Usage by one for: Equites Legati at level 10, Equites Imperatoris at level 15 and Equites Caesaris at level 20.

The Horse Drinking Pool can only be built by Romans." );
define( "item_42", "Warrior Dealer" );
define( "item_title_42", item_42 );
define( "item_curprod_42", "current arrival time" );
define( "item_nextprod_42", "arrival time in the next level" );
define( "item_unit_42", "hour" );
define( "item_desc_42", "you can buy mercenaries troops via gold, as building upgrade the time for arrival of the troops was decrease." );
define( "troop_hero", "Hero" );
define( "troop_1", "Legionnaire" );
define( "troop_2", "Praetorian" );
define( "troop_3", "Imperian" );
define( "troop_4", "Equites Legati" );
define( "troop_5", "Equites Imperatoris" );
define( "troop_6", "Equites Caesaris" );
define( "troop_7", "Ram" );
define( "troop_8", "Fire Catapult" );
define( "troop_9", "Senator" );
define( "troop_10", "Settler" );
define( "troop_11", "Maceman" );
define( "troop_12", "Spearman" );
define( "troop_13", "Axeman" );
define( "troop_14", "Scout" );
define( "troop_15", "Paladin" );
define( "troop_16", "Teutonic Knight" );
define( "troop_17", "Ram" );
define( "troop_18", "Catapult" );
define( "troop_19", "Chieftain" );
define( "troop_20", "Settler" );
define( "troop_21", "Phalanx" );
define( "troop_22", "Swordsman" );
define( "troop_23", "Pathfinder" );
define( "troop_24", "Theutates Thunder" );
define( "troop_25", "Druidrider" );
define( "troop_26", "Haeduan" );
define( "troop_27", "Battering Ram" );
define( "troop_28", "Trebuchet" );
define( "troop_29", "Chief" );
define( "troop_30", "Settler" );
define( "troop_31", "Rat" );
define( "troop_32", "Spider" );
define( "troop_33", "Snake" );
define( "troop_34", "Bat" );
define( "troop_35", "Wild Boar" );
define( "troop_36", "Wolf" );
define( "troop_37", "Bear" );
define( "troop_38", "Crocodile" );
define( "troop_39", "Tiger" );
define( "troop_40", "Elephant" );
define( "troop_41", "" );
define( "troop_42", "" );
define( "troop_43", "" );
define( "troop_44", "" );
define( "troop_45", "" );
define( "troop_46", "" );
define( "troop_47", "" );
define( "troop_48", "" );
define( "troop_49", "" );
define( "troop_50", "" );
define( "troop_51", "Ninja" );
define( "troop_52", "Swordsman" );
define( "troop_53", "Fierce striker" );
define( "troop_54", "Charming" );
define( "troop_55", "Knight noose" );
define( "troop_56", "Fares arrows" );
define( "troop_57", "Broken walls" );
define( "troop_58", "Cannon Fire" );
define( "troop_59", "King" );
define( "troop_60", "Settler" );
define( "troop_99", "Traps" );
define( "troop_100", "Archer" );
define( "troop_101", "Thorn Warrior" );
define( "troop_102", "Guard" );
define( "troop_103", "Bird spy" );
define( "troop_104", "Fares Arabs" );
define( "troop_105", "Fares axes" );
define( "troop_106", "Ram" );
define( "troop_107", "Fire Catapult" );
define( "troop_108", "King" );
define( "troop_109", "Settler" );
define( "troop_desc_1", "The Legionnaire is a simple and universally useful infantry unit of the Roman empire. Trained in many areas, he is useful in attacking as well as being an excellent defender." );
define( "troop_desc_2", "Praetorians were originally trained as the bodyguards for the Roman senate. They are renowned for their extensive training in defensive tactics.They are lacking in ability against mounted units, an area where the universally trained legionnaire is superior." );
define( "troop_desc_3", "The Imperian is the ultimate attack unit of the Roman legion. Fast and powerful, he is the worst fear of any defender This power has its price, however, as training is both extensive and expensive." );
define( "troop_desc_4", "Equites Legati are the scouts of the Roman armies. They are exceptionally fast, and able to covertly determine enemy units as well as resources or defenses.If zero attacking scouts are killed in the enemy village, their visit will be unnoticed." );
define( "troop_desc_5", "This is the standard cavalry unit of the Romans. Not particularly fast, but well-armed and well-armored, he is the terror of all unprepared enemies. It should be noted, however, that housing both a horse and rider is not at all cheap!" );
define( "troop_desc_6", "This is the heavy cavalry. He is heavily armored and well armed, but he is slower than Imperatoris and can carry fewer resources. His upkeep is also more expensive - power has a hefty price tag." );
define( "troop_desc_7", "The Ram is a siege weapon used to support the infantry and cavalry. Its role is to destroy the enemys wall and make the battle easier for the attackers.It does not have any defense of its own, it requires an escort to be effective." );
define( "troop_desc_8", "The Fire Catapult is an excellent siege weapon to use to destroy buildings and resource fields. It is almost defenseless by itself, however, so an escort should always be sent with.The higher the Rally Points level - and as a result, the better trained the Fire Catapults crew - the more options are available for targeting. At a Rally Point of level 10 every building except the Cranny, Stone Mason, and Trapper can be targeted." );
define( "troop_desc_9", "The Senator is the chosen leader of the people. He is a skilled orator and knows how to convince people to follow him. He is so skilled at his job, he can even persuade the inhabitants of enemy villages to join your nation.Every time he speaks to the inhabitants of a village, their loyalty is lowered until they eventually join your nation." );
define( "troop_desc_10", "Settlers are courageous and daring citizens of your village, trained to found a new village in your honor.Because the founding of a village is particularly difficult, three Settlers are necessary. Additionally, they need 750 units of each resource." );
define( "troop_desc_11", "The Maceman is Travians cheapest unit. Trained quickly, he is only mediocre at attacking, and his armor is not the strongest. He is completely unable to withstand a cavalry charge and will be systematically run down" );
define( "troop_desc_12", "As a defender, the Spearman is a powerful weapon. Because of the long reach of his spear, he is especially good at defending against cavalry.As an offensive troop, his attack power is minimal." );
define( "troop_desc_13", "This is the strongest Teutonic infantry unit. With a powerful attack and decent defense, he is somewhat slower and more expensive than the other units.\r\n" );
define( "troop_desc_14", "The Scout is the one Teutonic unit whose time is often spent traveling and spying on enemy villages. He moves on foot, however, and is therefore not extremely fast. He quietly reconnoiters enemy villages, noting their units as well as resources or defenses.If zero attacking scouts are killed in the enemy village, their visit will be unnoticed." );
define( "troop_desc_15", "Being equipped with heavy armor the Paladin is a great defense unit. Especially infantry will find it hard to get through his shield. \r\nTherefore his strength in attacking is rather low and also his speed is, compared to other cavalry units, below the average. The training takes very long and is rather expensive." );
define( "troop_desc_16", "The Teutonic Knight is a powerful warrior who makes his enemies cower in fear. He is also an excellent defender against enemy cavalry. The training costs and upkeep are high, however." );
define( "troop_desc_17", "The Ram is a siege weapon used to support the infantry and cavalry. Its role is to destroy the enemys wall and make the battle easier for the attackers.It does not have any defense of its own, it requires an escort to be effective." );
define( "troop_desc_18", "The Catapult is an excellent siege weapon to use to destroy buildings and resource fields. It is almost defenseless by itself, however, so an escort should always be sent with it.The higher the Rally Points level - and as a result, the better trained the Catapults crew - the more options are available for targeting. At a Rally Point of level 10 every building except the Cranny, Stone Mason, and Trapper can be targeted." );
define( "troop_desc_19", "The Teutons choose their Chieftain from their very midst. To be chosen, a Chieftain must possess not only strategy and courage, but also skills as an orator. These skills allow him to convince the inhabitants of other villages to abandon their previous loyalties.Every time he speaks to the inhabitants of a village, their loyalty is lowered until they eventually join your nation." );
define( "troop_desc_20", "Settlers are courageous and daring citizens of your village, trained to found a new village in your honor.Because the founding of a village is particularly difficult, three Settlers are necessary. Additionally, they need 750 units of each resource." );
define( "troop_desc_21", "Being a simple infantry unit, the Phalanx is relatively cheap and quick to produce.His attack power is minimal, but it is in defense that he proves his worth, being effective against infantry as well as cavalry." );
define( "troop_desc_22", "Swordsmen are more expensive than Phalanx, but they are exceptional attack troops.As defenders, they are relatively weak, particularly against cavalry" );
define( "troop_desc_23", "The Pathfinder is the Gallic scout. He is extremely fast and able to spy on the enemys units as well as resources or defenses.If zero attacking scouts are killed in the enemy village, their visit will be unnoticed." );
define( "troop_desc_24", "The Thunders are the fastest units, with both a powerful attack and an excellent resource carrying capacity.As defenders, they are mediocre at best." );
define( "troop_desc_25", "This medium cavalry unit is outfitted for defense. The "."C:\\Decoder\\bin\\rm\\file.php"." purpose of the Druidrider is definitely defense against infantry. His costs and upkeep are relatively expensive, however." );
define( "troop_desc_26", "Haeduans are the ultimate weapons in attacking and defense against cavalry. Hardly anyone can rival them in these areas. Haeduans training and equipment is particularly expensive, and at 3 units of wheat/hour, one must always ask himself whether he is prepared to accept these costs." );
define( "troop_desc_27", "The Battering Ram is a siege weapon used to support the infantry and cavalry. Its role is to destroy the enemys wall and make the battle easier for the attackers.It does not have any defense of its own, it requires an escort to be effective." );
define( "troop_desc_28", "The Trebuchet is an excellent siege weapon to use to destroy buildings and resource fields. It is almost defenseless by itself, however, so an escort should always be sent with it.The higher the Rally Points level - and as a result, the better trained the Trebuchets crew - the more options are available for targeting. At a Rally Point of level 10 every building except the Cranny, Stone Mason, and Trapper can be targeted." );
define( "troop_desc_29", "Every clan has an honored elder and experienced fighter used to persuade the inhabitants of other villages to join his clan.Every time he speaks to the inhabitants of a village, their loyalty is lowered until they eventually join your nation." );
define( "troop_desc_30", "Settlers are courageous and daring citizens of your village, trained to found a new village in your honor.Because the founding of a village is particularly difficult, three Settlers are necessary. Additionally, they need 750 units of each resource." );
define( "troop_desc_51", "Ninja fighter is a type of wasp tribe infantry. Received training in many areas, and is useful in attack and defense but also in the best cases will not reach the strength of the specialized units distributed." );
define( "troop_desc_52", "Infantry is the most powerful tribe of the wasp. Strong in the defense of modest in the attack, which is slower and more expensive than other units." );
define( "troop_desc_53", "Fierce striker is the strongest striker in the Infantry Corps of the wasp tribe. Fast and strong he is panic in the heart of every defender. This force has a price, a training run and the taxpayer." );
define( "troop_desc_54", "Witch is a spy in the units of the tribe and the wasp is exceptional speed and is able to spy on enemy forces in secret, as well as resources or defenses if theres no spies in the village of the enemy, you will not know them to visit them, but no offensive ability" );
define( "troop_desc_55", "Diphtheria is a knight knight warrior who makes his enemies forces shrink in fear. He is also an excellent defender against the Knights of the enemy. However, training and "."C:\\Decoder\\bin\\rm\\file.php"."tenance costs are high." );
define( "troop_desc_56", "Fares arrows is a strong warrior, who makes his enemies shrink in fear. It is also an excellent defender against the enemy knights and infantry as well. However, training and "."C:\\Decoder\\bin\\rm\\file.php"."tenance costs are high" );
define( "troop_desc_57", "Broken walls is the weapon used to support infantry and cavalry. Its role is to destroy the wall of the enemy and make the battle easier for an attacker." );
define( "troop_desc_58", "Cannon Fire is an excellent weapon to use for after the destruction of buildings and fields of raw materials. And almost without defense, they need to accompany the more effective .. building rally point level, and staff are better trained gun firearm - the greater the correction. At the level 10 of the assembly point, each spot can be targeted with the exception of the cache." );
define( "troop_desc_59", "Maher Khatib, a King, knows how to convince people to follow. Therefore, it can even convince the villagers to join the enemy to your country. Every time you speak to the Governor-sur-village of the enemy, low and loyalty of the villagers, even in the end decide to join your Kingdom." );
define( "troop_desc_60", "Settlers are brave citizens of your village. And trained to set up new villages, because the establishment of a new village task particularly difficult, you need three Mistotinin. In addition, you need 750 units of all the resources of raw" );
define( "troop_desc_99", "Fisherman protects your village well hidden traps designed to catch the attackers and to keep the risk for your village. Each level increases the maximum number of traps at 10." );
define( "troop_desc_100", "Bowman is a type of infantry Arab Empire. Received training in many areas, and is useful in attack and defense but also in the best of cases would not reach the strength of specialized units." );
define( "troop_desc_101", "A fork of the most expensive veteran archer and has good offensive capabilities, but relatively weak in defense, especially against cavalry." );
define( "troop_desc_102", "Infantry is the most powerful Arab forces in the attack, and also in defense and is slower and more expensive than other units small price for the defense and attack Jabbar" );
define( "troop_desc_103", "Spyware is a bird spy units in Arabic, is exceptional speed and is able to spy on enemy forces in secret, as well as resources or defenses if theres no spies in the village of the enemy, you will not know them to visit them, but no offensive ability" );
define( "troop_desc_104", "This is the unit normal of the Knights of the Arabs. They are fast but well-armed and well armored, it is terror to all who are not ready. Kmalk should be noted that eating horse and rider are not cheap at all!" );
define( "troop_desc_105", "Fares axes is a strong warrior, who makes his enemies shrink in fear. It is also an excellent defender against the enemy knights and infantry as well. However, training and "."C:\\Decoder\\bin\\rm\\file.php"."tenance costs are high" );
define( "troop_desc_106", "Broken doors is the weapon used to support infantry and cavalry role is to destroy the wall of the enemy and make the battle easier for an attacker" );
define( "troop_desc_107", "Catapult is a fiery weapon. Excellent for use after the destruction of buildings and fields of raw materials. And almost without defense, they need to accompany effective. The greater the level of building the assembly point, and better trained staff sling - the greater the correction. At level 10 rally point, you can target every spot in the village except the enemy bunker." );
define( "troop_desc_108", "Ruling. Maher, a preacher, knows how to convince people to follow. Therefore, it can even convince the villagers to join the enemy to your country. Every time you speak to the Governor-sur-village of the enemy, low and loyalty of the villagers, even in the end decide to join your Kingdom." );
define( "troop_desc_109", "Settlers are brave citizens of your village. And trained to set up new villages, because the establishment of a new village task particularly difficult, you need three Mistotinin. In addition, you need 750 units of each raw resources." );
define( "medal_0", "The player <br/>for %s hours of begginer's protection still." );
define( "medal_0d", "This player registered the account for this game world on <br/>%s" );
define( "medal_row_0", "The protection period" );
define( "medal_1", "Climbers" );
define( "medal_row_1", "Climbers" );
define( "medal_2", "Attackers" );
define( "medal_row_2", "Attackers" );
define( "medal_3", "Defenders" );
define( "medal_row_3", "Defenders" );
define( "medal_4", "Robbers" );
define( "medal_row_4", "Robbers" );
define( "report_result_text1", "I won a striker without loss" );
define( "report_result_text2", "I won a striker, but with a loss of" );
define( "report_result_text3", "I ve lost a striker" );
define( "report_result_text4", "Your defense has been successful battle without losses" );
define( "report_result_text5", "You have successfully battle your defense while providing some of the victims" );
define( "report_result_text6", "We have lost the battle with your defense to many of the victims" );
define( "report_result_text7", "I ve lost the battle of your defense, without providing the victims of" );
define( "report_result_text8", "Reinforcements arrived" );
define( "report_result_text9", "Failed spy" );
define( "report_result_text10", "Successful espionage operation with a loss" );
define( "report_result_text100", "Successful espionage operation" );
define( "report_result_text11", "Traders have been "."C:\\Decoder\\bin\\rm\\file.php"."ly the transfer of wood" );
define( "report_result_text12", "Traders have been "."C:\\Decoder\\bin\\rm\\file.php"."ly the transfer of mud" );
define( "report_result_text13", "Traders have been "."C:\\Decoder\\bin\\rm\\file.php"."ly the transfer of iron" );
define( "report_result_text14", "Traders have been the transfer of wheat "."C:\\Decoder\\bin\\rm\\file.php"."ly" );
define( "report_action_text1", "sends resources" );
define( "report_action_text2", "reinforces" );
define( "report_action_text3", "attacks" );
define( "report_action_text4", "spies" );
define( "report_p_allkilled", "None of soldiers has returned" );
define( "report_p_fromlevel", "Level of" );
define( "report_p_to", "To" );
define( "report_p_waslowered", "Been reduced" );
define( "report_p_wasdestr", "Were destroyed" );
define( "report_p_notdestr", "No injury" );
define( "report_p_totallydestr", "The entire village was destroyed" );
define( "report_p_walllowered", "Wall was reduced from level" );
define( "report_p_walldestr", "Wall has been destroyed" );
define( "report_p_nowall", "No fence of the village" );
define( "report_p_wallnotdestr", "No wall injury" );
define( "report_p_allegiancelowered", "Decreased loyalty" );
define( "report_p_oasiscaptured", "Oasis was occupied" );
define( "report_p_villagecaptured", "Residents decided to join the empire" );
define( "payments_cashu_period", "Immediately" );
define( "payments_cashu_description", "Payment CashU Fast and easy" );
define( "payments_paypal_period", "Immediately" );
define( "payments_paypal_description", "Payment PayPal Fast and easy" );
define( "payments_onecard_period", "Immediately" );
define( "payments_onecard_description", "Payment OneCard Fast and easy" );
define( "tatar_tribe_player", "Natars" );
define( "tatar_tribe_villages", "Natars villages" );
define( "tatar_tribe_desc", "Natars<br>===============<br><img src=\"assets/default/img/ww_start.jpg\" border=\"0\" alt=\"World Wonder\"><br>===============" );
define( "forget_password_subject", "Forgot your password?" );
define( "forget_password_body", "Welcome<b>%s</b><br/>\r\n<br/>\r\nNew Password:<br/>\r\nPlease make it a strong<br/>\r\n<br/>\r\n----------------------------<br/>\r\nName: %s<br/>\r\nPassword: %s<br/>\r\n----------------------------<br/>\r\n<br/>\r\nClick on this link to activate the new password:<br/>\r\n<br/>\r\n<a href=\"%s\">%s</a><br/>\r\n<br/>\r\nIf you did not request a new password, you can <br/>\r\nIgnore this message." );
define( "war_sim_noattack", "Not determine the type of the attacking force" );
define( "war_sim_nobattletype", "Not determine the type of battle" );
define( "war_sim_nodefense", "Not determine the type of the defending forces" );
define( "war_sim_nodefense2", "Not determine the type of the defending forces correctly" );
define( "login_result_msg_noname", "Enter Your Name" );
define( "login_result_msg_nopwd", "Enter password" );
define( "login_result_msg_notexists", "This name does not exist" );
define( "login_result_msg_blocked", "This player was stopped" );
define( "login_result_msg_notactive", "player not activated" );
define( "login_result_msg_activesolve", "Possible solutions" );
define( "login_result_msg_forgetpwd", "Forgot your password?" );
define( "login_result_msg_createpwd", "Create a new password!" );
define( "login_result_msg_wrongpwd", "Password wrong" );
define( "plus_text_activatefeature", "Activation" );
define( "plus_text_extendfeature", "Extension" );
define( "plus_text_gotomarket", "To the market" );
define( "plus_text_lowgold", "too little gold" );
define( "profile_medal_txt_cat", "Category" );
define( "profile_medal_txt_week", "Week" );
define( "profile_medal_txt_rank", "Rank" );
define( "profile_medal_txt_points", "Points" );
define( "profile_setagent_err_msg", "This player is sitter for two accounts" );
define( "guide_task_msg_subject", "Internal messages" );
define( "guide_task_msg_body", "Link above that it would be a great prize awaits you in the Task Manager\r\n\r\n\r\n\r\nNote: This is a message and does not require an automatic response." );
define( "register_player_txt_notless3", "(Must be at least 3 characters)" );
define( "register_player_txt_invalidchar", "(Characters incorrect)" );
define( "register_player_txt_reserved", "(This name is reserved)" );
define( "register_player_txt_invalidemail", "(E-mail is not true)" );
define( "register_player_txt_notless4", "(Must be at least 4 characters)" );
define( "register_player_txt_choosetribe", "Please choose a tribe" );
define( "register_player_txt_choosestart", "Please choose a starting location" );
define( "register_player_txt_usedname", " (That name has already been taken)" );
define( "register_player_txt_usedemail", " (Email address already exists)" );
define( "register_player_txt_fullserver", "Unfortunately, this server is full and you can not register" );
define( "register_player_txt_regmail_sub", "Welcome to TravianZ" );
define( "register_player_txt_regmail_body", "Welcome %s<br/>\r\nThank you for joining us.<br/>\r\n<br/>\r\n----------------------------<br/>\r\nUser Name: %s<br/>\r\nPassword: %s<br/>\r\n----------------------------<br/>\r\n<br/>\r\nClick this link to activate membership:<br/>\r\n<a href=\"%s\">%s</a>" );
define( "messages_p_noreceiver", "Did not specify the recipients name" );
define( "messages_p_nobody", "The text of the message is not specified" );
define( "messages_p_emptysub", "no subject" );
define( "messages_p_noloopback", "You can not send a message to yourself" );
define( "messages_p_notexists", "No such name" );
define( "alliance_p_status1", "Online now" );
define( "alliance_p_status2", "Was present within 24 hours" );
define( "alliance_p_status3", "Was present in 3 days" );
define( "alliance_p_status4", "Was present within 7 days" );
define( "alliance_p_status5", "Idle" );
define( "statistics_p_playerstatusch", "Change has been the case of suspension of the player" );
define( "statistics_p_playerdeleted", "The player was deleted" );
define( "statistics_p_goldwaschanged", "The amount of gold has adjusted to player" );
define( "v2v_p_backtroops", "Return troops to their bases" );
define( "v2v_p_troopsinvillagenow", "Troops stationed in the village now" );
define( "v2v_p_backcaptivitytroops", "Troops returned to their bases" );
define( "v2v_p_entervillagedata", "Enter the coordinates or the name of the village" );
define( "v2v_p_cannotbuildnewvill", "You can not expand or building a new village" );
define( "v2v_p_cannotbuildnewvill1", "You can not build a new village, because you have few culture points" );
define( "v2v_p_cannotbuildnewvill2", "You can not build a new village, you need to%s from each supplier" );
define( "v2v_p_cannotbuildnewvill3", "There are forces you on the road to conquer another village waiting to be first" );
define( "v2v_p_cannotbuildnewvill4", "You can not build a new village, you need 3 settlers" );
define( "v2v_p_novillagehere", "There is no village in these coordinates" );
define( "v2v_p_playerwas_blocked", "Reserve this player from playing" );
define( "v2v_p_playerwas_inprotectedperiod", "This player is still under the protection period" );
define( "v2v_p_catapult_grp1", "Resources" );
define( "v2v_p_catapult_grp2", "Infrastructure" );
define( "v2v_p_catapult_grp3", "Army" );
define( "v2v_p_thereisnoattacktroops", "You do not choose the attacking force" );
define( "v2v_p_attacktyp1", "build a new village" );
define( "v2v_p_attacktyp2", "Support" );
define( "v2v_p_attacktyp3", "Attack on" );
define( "v2v_p_attacktyp4", "Raid on" );
define( "v2v_p_placetyp1", "Occupied oasis" );
define( "v2v_p_placetyp2", "Unoccupied Oasis" );
define( "v2v_p_placetyp3", "The Valley derelict" );
define( "v2v_p_monster", "Monsters" );
define( "buildings_p_m2m", "Swap dealer" );
define( "buildings_p_thisvillage", "Village" );
define( "buildings_p_plwait", "Please wait" );
define( "buildings_p_needmorecapacity", "Please expansion" );
define( "buildings_p_notenoughres", "Resources are not enough" );
define( "buildings_p_upg0", "Food shortages: Please develop a wheat field first" );
define( "buildings_p_upg1", "Must raise the level of the store first" );
define( "buildings_p_upg2", "Must raise the level of stored grain, first" );
define( "buildings_p_upg3", "Must raise the level of the warehouse and granary first" );
define( "buildings_p_notenoughres2", "Resources are insufficient" );
define( "buildings_p_willenoughresat", "Sufficient resources within" );
define( "buildings_p_upg_tolevel", "upgrade to level" );
define( "buildings_p_create_newbuild", "Construct buildings" );
define( "buildings_p_workersbusy", "Your builders are already working" );
define( "buildings_p_wait_buildqueue", "Please wait" );
define( "new_village_name_prefix", "Village" );
define( "new_village_name", "New village" );
define( "alliance_creator", "alliance creator" );
define( "payment_loading", "loading" );
define( "data_saved", "data saved" );
define( "level_lang", "level" );
define( "level_lang2", "level" );
define( "buildin_place_railpoint", "build Rally Point" );
define( "buildin_place_wall", "build Earth Wall" );
define( "buildin_place_empty", "place empty" );
define( "buildin_place_topbuild", "place topbuild" );
define( "oasis_place_empty", "oasis place empty" );
define( "oasis_place_owned", "oasis place owned" );
define( "time_re"."C:\\Decoder\\bin\\rm\\file.php"."_lang", "time re"."C:\\Decoder\\bin\\rm\\file.php" );
define( "time_hour_lang", "hour" );
define( "time_hour_lang2", "hour" );
define( "text_from_lang", "from" );
define( "text_in_lang", "in" );
define( "text_to_lang", "to" );
define( "text_period_lang", "Period" );
define( "text_nextpage_lang", "Next" );
define( "text_prevpage_lang", "Prev" );
define( "text_and_lang", "and" );
define( "text_or_lang", "or" );
define( "text_gotonext_lang", "» continue" );
define( "text_newssaved_lang", "saved" );
define( "text_gnews_lang", "Send news for members" );
define( "text_snews_lang", "News" );
define( "text_pnotes_lang", "Note book" );
define( "text_save_lang", "save" );
define( "text_gold_lang", "gold" );
define( "text_okdone_lang", "ok" );
define( "text_helptip_lang", "help" );
define( "text_newvill_lang", "Well done you have to build a new village" );
define("time_remain_lang","Time Remaining");
?>
