<?php
/*********************/
/*                   */
/*  Version : 5.1.0  */
/*  Author  : RM     */
/*  Comment : 071223 */
/*                   */
/*********************/

define( "LANGUI_CUSTBU_CRANNYEXTRA", "Ammount of hidden resources" );
define( "LANGUI_CUSTBU_M_DROP", "Building demolition" );
define( "LANGUI_CUSTBU_M_DROPDESC", "If you no longer need a building, you can order the demolition of the building." );
define( "LANGUI_CUSTBU_M_CANCEL", "cancel the demolition" );
define( "LANGUI_CUSTBU_M_EMPTY", "empty" );
define( "LANGUI_CUSTBU_M_DROPBTN", "destruction" );
define( "LANGUI_CUSTBU_TRP_t1", "currently have" );
define( "LANGUI_CUSTBU_TRP_t2", "and of the traps" );
define( "LANGUI_CUSTBU_TRP_t3", "where prisoners" );
define( "LANGUI_CUSTBU_TRP_t4", "name" );
define( "LANGUI_CUSTBU_TRP_t5", "Qty" );
define( "LANGUI_CUSTBU_TRP_t6", "maximum" );
define( "LANGUI_CUSTBU_TRP_t7", "available" );
define( "LANGUI_CUSTBU_TRP_t8", "No troops currently in training" );
define( "LANGUI_CUSTBU_TRP_t9", "train" );
define( "LANGUI_CUSTBU_TRP_t10", "under the production" );
define( "LANGUI_CUSTBU_TRP_t11", "under training" );
define( "LANGUI_CUSTBU_TRP_t12", "be ready in" );
define( "LANGUI_CUSTBU_TRP_t13", "trap" );
define( "LANGUI_CUSTBU_TRP_t14", "Next unit" );
define( "LANGUI_CUSTBU_TRP_t15", "orders to complete troops training in this village immediately<br>Cost %s Gold " );
define( "LANGUI_CUSTBU_TRP_t16", "orders to complete troops training immediately" );
define( "LANGUI_CUSTBU_TRP_t17", "Costs" );
define( "LANGUI_CUSTBU_TRP_t18", "gold" );
define( "LANGUI_CUSTBU_TRP_t19", "troops were sent to your village" );
define( "LANGUI_CUSTBU_TRP_t20", "you don't have enough gold" );
define( "LANGUI_CUSTBU_EMB_t1", "Alliance" );
define( "LANGUI_CUSTBU_EMB_t2", "code" );
define( "LANGUI_CUSTBU_EMB_t3", "the Alliance" );
define( "LANGUI_CUSTBU_EMB_t4", "Alliance building" );
define( "LANGUI_CUSTBU_EMB_t5", "write code" );
define( "LANGUI_CUSTBU_EMB_t6", "user code from someone else" );
define( "LANGUI_CUSTBU_EMB_t7", "name" );
define( "LANGUI_CUSTBU_EMB_t8", "type the name" );
define( "LANGUI_CUSTBU_EMB_t9", "completely" );
define( "LANGUI_CUSTBU_EMB_t10", "join the alliance" );
define( "LANGUI_CUSTBU_EMB_t11", "Refuse" );
define( "LANGUI_CUSTBU_EMB_t12", "Accept" );
define( "LANGUI_CUSTBU_EMB_t13", "There are no invitations yet" );
define( "LANGUI_CUSTBU_EMB_t14", "This alliance don't have spaces" );
define( "LANGUI_CUSTBU_TWH_t1", "municipal" );
define( "LANGUI_CUSTBU_TWH_t2", "activity" );
define( "LANGUI_CUSTBU_TWH_t3", "small celebration" );
define( "LANGUI_CUSTBU_TWH_t4", "culture points" );
define( "LANGUI_CUSTBU_TWH_t5", "celebration" );
define( "LANGUI_CUSTBU_TWH_t6", "big celebration" );
define( "LANGUI_CUSTBU_TWH_t7", "celebration" );
define( "LANGUI_CUSTBU_BLK_t1", "activity" );
define( "LANGUI_CUSTBU_BLK_t2", "No units is currently developing" );
define( "LANGUI_CUSTBU_BLK_t3", "developments" );
define( "LANGUI_CUSTBU_BLK_t4", "upgrade" );
define( "LANGUI_CUSTBU_ACD_t1", "Military Academy" );
define( "LANGUI_CUSTBU_ACD_t2", "activity" );
define( "LANGUI_CUSTBU_ACD_t3", "Can not research new troops now.To review the terms of the research of new troops click on troops images in the Quick Guide" );
define( "LANGUI_CUSTBU_ACD_t4", "more" );
define( "LANGUI_CUSTBU_ACD_t5", "conditions" );
define( "LANGUI_CUSTBU_ACD_t6", "less" );
define( "LANGUI_CUSTBU_ACD_t7", "research" );
define( "LANGUI_CUSTBU_ACD_t8", "search" );
define( "LANGUI_CUSTBU_RPLC_p1", "training" );
define( "LANGUI_CUSTBU_RPLC_p2", "culture points" );
define( "LANGUI_CUSTBU_RPLC_p3", "loyalty" );
define( "LANGUI_CUSTBU_RPLC_p4", "expand" );
define( "LANGUI_CUSTBU_RPLC_p1_t1", "name" );
define( "LANGUI_CUSTBU_RPLC_p1_t2", "Qty" );
define( "LANGUI_CUSTBU_RPLC_p1_t3", "maximum" );
define( "LANGUI_CUSTBU_RPLC_p1_t4", "available" );
define( "LANGUI_CUSTBU_RPLC_p1_t5", "train" );
define( "LANGUI_CUSTBU_RPLC_p1_t6", "You can not create other villages from this village" );
define( "LANGUI_CUSTBU_RPLC_p1_t7", "to build or occupy another village, you need to upgrade the building to level" );
define( "LANGUI_CUSTBU_RPLC_p1_t8", "you can now build a new village" );
define( "LANGUI_CUSTBU_RPLC_p1_t9", "to build or occupy another village, you need to upgrade the building to level 10" );
define( "LANGUI_CUSTBU_RPLC_p1_t10", "under training" );
define( "LANGUI_CUSTBU_RPLC_p1_t11", "the next unit is not ready yet" );
define( "LANGUI_CUSTBU_RPLC_p1_t12", "this village is your capital" );
define( "LANGUI_CUSTBU_RPLC_p1_t13", "make this village your capital" );
define( "LANGUI_CUSTBU_RPLC_p2_t1", "To be able to expand your empire you need culture points. These points accumulate over time and will be added to your village, which is faster in the higher levels." );
define( "LANGUI_CUSTBU_RPLC_p2_t2", "production of this village" );
define( "LANGUI_CUSTBU_RPLC_p2_t3", "Culture points of a day" );
define( "LANGUI_CUSTBU_RPLC_p2_t4", "Production of all the villages" );
define( "LANGUI_CUSTBU_RPLC_p2_t5", "village produced" );
define( "LANGUI_CUSTBU_RPLC_p2_t6", "culture points until now" );
define( "LANGUI_CUSTBU_RPLC_p2_t7", "the establishment of a new village or occupation requires you to have" );
define( "LANGUI_CUSTBU_RPLC_p2_t8", "culture points" );
define( "LANGUI_CUSTBU_RPLC_p3_t1", "Attacks the leaders or elders or superiors reduce the loyalty of the village. when it reaches zero loyalty to village will join the Kingdom of the attacker" );
define( "LANGUI_CUSTBU_RPLC_p3_t2", "the loyalty of the village is now" );
define( "LANGUI_CUSTBU_RPLC_p4_t1", "villages founded or colonized from this village" );
define( "LANGUI_CUSTBU_RPLC_p4_t2", "village" );
define( "LANGUI_CUSTBU_RPLC_p4_t3", "population" );
define( "LANGUI_CUSTBU_RPLC_p4_t4", "coordinates" );
define( "LANGUI_CUSTBU_RPLC_p4_t5", "Date" );
define( "LANGUI_CUSTBU_RPLC_p4_t6", "not established or occupies another village from this village" );
define( "LANGUI_CUSTBU_HRO_p1", "hero" );
define( "LANGUI_CUSTBU_HRO_p2", "Oasis" );
define( "LANGUI_CUSTBU_HRO_p1_t1", "list of heroes" );
define( "LANGUI_CUSTBU_HRO_p1_t2", "No troops currently in training" );
define( "LANGUI_CUSTBU_HRO_p1_t3", "your hero is being trained and will be ready" );
define( "LANGUI_CUSTBU_HRO_p1_t4", "experience" );
define( "LANGUI_CUSTBU_HRO_p1_t5", "name of the hero" );
define( "LANGUI_CUSTBU_HRO_p1_t6", "completely" );
define( "LANGUI_CUSTBU_HRO_p1_t7", "train" );
define( "LANGUI_CUSTBU_HRO_p2_t1", "Oasis" );
define( "LANGUI_CUSTBU_HRO_p2_t2", "name" );
define( "LANGUI_CUSTBU_HRO_p2_t3", "coordinates" );
define( "LANGUI_CUSTBU_HRO_p2_t4", "loyalty" );
define( "LANGUI_CUSTBU_HRO_p2_t5", "resources" );
define( "LANGUI_CUSTBU_HRO_p2_t6", "left Oasis" );
define( "LANGUI_CUSTBU_HRO_p2_t7", "Oasis occupied" );
define( "LANGUI_CUSTBU_HRO_p2_t8", "Cancel to leave the oasis" );
define( "LANGUI_CUSTBU_RP_p1", "Overview" );
define( "LANGUI_CUSTBU_RP_p2", "Send troops" );
define( "LANGUI_CUSTBU_RP_p3", "battle simulator" );
define( "LANGUI_CUSTBU_RP_t1", "incoming troops" );
define( "LANGUI_CUSTBU_RP_t2", "Return to" );
define( "LANGUI_CUSTBU_RP_t3", "attack on" );
define( "LANGUI_CUSTBU_RP_t4", "raid on" );
define( "LANGUI_CUSTBU_RP_t5", "Nature" );
define( "LANGUI_CUSTBU_RP_t6", "units" );
define( "LANGUI_CUSTBU_RP_t7", "access" );
define( "LANGUI_CUSTBU_RP_t8", "booty" );
define( "LANGUI_CUSTBU_RP_t9", "forces on the road" );
define( "LANGUI_CUSTBU_RP_t10", "promote" );
define( "LANGUI_CUSTBU_RP_t11", "spy on" );
define( "LANGUI_CUSTBU_RP_t12", "building a new village" );
define( "LANGUI_CUSTBU_RP_t13", "Occupied Oasis" );
define( "LANGUI_CUSTBU_RP_t14", "Unoccupied Oasis" );
define( "LANGUI_CUSTBU_RP_t15", "resources" );
define( "LANGUI_CUSTBU_RP_t16", "Troops in the village" );
define( "LANGUI_CUSTBU_RP_t17", "Units" );
define( "LANGUI_CUSTBU_RP_t18", "Upkeep" );
define( "LANGUI_CUSTBU_RP_t19", "per hour" );
define( "LANGUI_CUSTBU_RP_t20", "return" );
define( "LANGUI_CUSTBU_RP_t21", "captured" );
define( "LANGUI_CUSTBU_RP_t22", "the launch of the troops" );
define( "LANGUI_CUSTBU_RP_t23", "troops in other villages" );
define( "LANGUI_CUSTBU_RP_t24", "withdraw all" );
define( "LANGUI_CUSTBU_RP_t25", "my troops when captured" );
define( "LANGUI_CUSTBU_RP_t26", "Oasis colony" );
define( "LANGUI_CUSTBU_RP_t27", "cancel" );
define( "LANGUI_CUSTBU_MKT_p1", "send resources" );
define( "LANGUI_CUSTBU_MKT_p2", "purchase" );
define( "LANGUI_CUSTBU_MKT_p3", "sell" );
define( "LANGUI_CUSTBU_MKT_p4", "dealer swap" );
define( "LANGUI_CUSTBU_MKT_p1_t1", "merchants" );
define( "LANGUI_CUSTBU_MKT_p1_t2", "village" );
define( "LANGUI_CUSTBU_MKT_p1_t3", "player" );
define( "LANGUI_CUSTBU_MKT_p1_t4", "village not found" );
define( "LANGUI_CUSTBU_MKT_p1_t5", "insufficient resources" );
define( "LANGUI_CUSTBU_MKT_p1_t6", "no selection of raw materials" );
define( "LANGUI_CUSTBU_MKT_p1_t7", "few merchants, you need to raise your marketplace" );
define( "LANGUI_CUSTBU_MKT_p1_t8", "dealer" );
define( "LANGUI_CUSTBU_MKT_p1_t9", "Tjarkm already in the village" );
define( "LANGUI_CUSTBU_MKT_p1_t10", "Merchants are unable to carry" );
define( "LANGUI_CUSTBU_MKT_p1_t11", "resources" );
define( "LANGUI_CUSTBU_MKT_p1_t12", "Traders coming" );
define( "LANGUI_CUSTBU_MKT_p1_t13", "Transport to" );
define( "LANGUI_CUSTBU_MKT_p1_t14", "Time" );
define( "LANGUI_CUSTBU_MKT_p1_t15", "Hours" );
define( "LANGUI_CUSTBU_MKT_p1_t16", "Resources" );
define( "LANGUI_CUSTBU_MKT_p1_t17", "traders travelers" );
define( "LANGUI_CUSTBU_MKT_p1_t18", "return from" );
define( "LANGUI_CUSTBU_MKT_p1_t19", "to transport" );
define( "LANGUI_CUSTBU_MKT_p1_t20", "number of merchants" );
define( "LANGUI_CUSTBU_MKT_p2_t1", "offers in the marketplace" );
define( "LANGUI_CUSTBU_MKT_p2_t2", "before me" );
define( "LANGUI_CUSTBU_MKT_p2_t3", "wanted me" );
define( "LANGUI_CUSTBU_MKT_p2_t4", "players" );
define( "LANGUI_CUSTBU_MKT_p2_t5", "activity" );
define( "LANGUI_CUSTBU_MKT_p2_t6", "You do not have sufficient resources" );
define( "LANGUI_CUSTBU_MKT_p2_t7", "Few merchants" );
define( "LANGUI_CUSTBU_MKT_p2_t8", "accept the offer" );
define( "LANGUI_CUSTBU_MKT_p2_t9", "no offers" );
define( "LANGUI_CUSTBU_MKT_p2_t10", "marketplace" );
define( "LANGUI_CUSTBU_MKT_p2_t11", "was to accept the offer of" );
define( "LANGUI_CUSTBU_MKT_p2_t12", "on its way to you" );
define( "LANGUI_CUSTBU_MKT_p2_t13", "the merchants were sent" );
define( "LANGUI_CUSTBU_MKT_p3_t1", "width" );
define( "LANGUI_CUSTBU_MKT_p3_t2", "maximum transfer time" );
define( "LANGUI_CUSTBU_MKT_p3_t3", "search" );
define( "LANGUI_CUSTBU_MKT_p3_t4", "only members of the alliance" );
define( "LANGUI_CUSTBU_MKT_p3_t5", "this offer is exaggerated and is fit" );
define( "LANGUI_CUSTBU_MKT_p3_t6", "Show Invalid" );
define( "LANGUI_CUSTBU_MKT_p3_t7", "the resources are not specified" );
define( "LANGUI_CUSTBU_MKT_p3_t8", "completely" );
define( "LANGUI_CUSTBU_MKT_p3_t9", "MY" );
define( "LANGUI_CUSTBU_MKT_p3_t10", "Alliance" );
define( "LANGUI_CUSTBU_MKT_p3_t11", "Delete view" );
define( "LANGUI_CUSTBU_MKT_p3_t12", "no" );
define( "LANGUI_CUSTBU_MKT_p3_t13", "yes" );
define( "LANGUI_CUSTBU_MKT_p4_t1", "Distribute the resources. (Step 1 of 2)" );
define( "LANGUI_CUSTBU_MKT_p4_t2", "Total" );
define( "LANGUI_CUSTBU_MKT_p4_t3", "rest" );
define( "LANGUI_CUSTBU_MKT_p4_t4", "You do not have enough gold." );
define( "LANGUI_CUSTBU_MKT_p4_t5", "Complete trade" );
define( "LANGUI_CUSTBU_MKT_p4_t6", "cost" );
define( "LANGUI_CUSTBU_MKT_p4_t7", "return" );
define( "LANGUI_CUSTBU_MKT_p4_t8", "gold" );
define( "LANGUI_CUSTBU_MKT_p4_t9", "You can distribute the raw materials in Marketplace with swap dealers as they want. <br> <br>\r\nThe first row shows the current contents of the store. <br>\r\nIn the second row you can distribute various resources. <br>\r\nThird row shows the difference between the quantities of old and new " );
?>
