<?php
/*********************/
/*                   */
/*  Version : 5.1.0  */
/*  Author  : RM     */
/*  Comment : 071223 */
/*                   */
/*********************/

define( "LANGUI_GUIDE_T1", " Welcome to TravianX!" );
define( "LANGUI_GUIDE_T2", "\"I see you have been made Senator of this little village. I will be your counselor for the first few days, and will never leave your side." );
define( "LANGUI_GUIDE_T3", "To the first quest!" );
define( "LANGUI_GUIDE_T4", "Look around on your own" );
define( "LANGUI_GUIDE_T5", "Skip Quests" );
define( "LANGUI_GUIDE_T6", "Quest 1: Woodcutter" );
define( "LANGUI_GUIDE_T7", "Around your village there are four green forests. Construct a Woodcutter,one of them. Wood is an important resource for our new settlement." );
define( "LANGUI_GUIDE_T8", "Construct a Woodcutter." );
define( "LANGUI_GUIDE_T9", "Yes, this way you produce more wood" );
define( "LANGUI_GUIDE_T10", "Continue with the next quest" );
define( "LANGUI_GUIDE_T11", "Quest 2: Wheat" );
define( "LANGUI_GUIDE_T12", "Now your subjects are hungry from working all day. Extend a Wheat Field to improve your subjects supply. Come back here once the building is complete." );
define( "LANGUI_GUIDE_T13", "Order" );
define( "LANGUI_GUIDE_T14", "Extend one Wheat Field" );
define( "LANGUI_GUIDE_T15", "Very good. Now your subjects have enough to eat again..." );
define( "LANGUI_GUIDE_T16", "<b><font color=\"#71D000\">P</font><font color=\"#FF6F0F\">l</font><font color=\"#FF6F0F\">us</font></b>" );
define( "LANGUI_GUIDE_T17", "Quest 3: Your villages name" );
define( "LANGUI_GUIDE_T18", "Use your creativity to grant your village the ultimate name!<br><br>Click on \"Profile\" on the left hand menu and then select Change profile ..." );
define( "LANGUI_GUIDE_T19", "Change your village name to something nice" );
define( "LANGUI_GUIDE_T20", "Excellent, you have to choose a great name for your village, youre about to you to choose the same name also" );
define( "LANGUI_GUIDE_T21", "Prize" );
define( "LANGUI_GUIDE_T22", "Quest 4: Players" );
define( "LANGUI_GUIDE_T23", "TravianX is a big game,played by millions of other players, click on the icon \"statistics\" in the top menu and then enter a number here, your ranking" );
define( "LANGUI_GUIDE_T24", "Then find your ranking in the statistics and then enter it here" );
define( "LANGUI_GUIDE_T25", "No, no. You must enter your ranking <i> </i> here. Ranking just a number" );
define( "LANGUI_GUIDE_T26", "Well, if played well up to that place in one day. I'm going to give you some resources" );
define( "LANGUI_GUIDE_T27", "Well, you're better than that. I'm going to give you some resources" );
define( "LANGUI_GUIDE_T28", "Excellent! This is your ranking correct" );
define( "LANGUI_GUIDE_T29", "Quest 5: two applications for construction" );
define( "LANGUI_GUIDE_T30", "Build iron mine and clay pit, as the iron and clay of the village wanted a lot<br><br>All thanks to the account<b><font color=\"#71D000\">P</font><font color=\"#FF6F0F\">L</font><font color=\"#71D000\">U</font><font color=\"#FF6F0F\">S</font></b>That you have gifted it to you just before you where you can give commands to develop together Monday" );
define( "LANGUI_GUIDE_T31", "Develop Iron Mine and one" );
define( "LANGUI_GUIDE_T32", "Develop a mud hole and one" );
define( "LANGUI_GUIDE_T33", "As noted, orders the construction takes a long time for implementation. World war, the Tatars and working until you are not online on the Internet, even after several months of playing you will find there are new things to discover<br><br>The best what can be done is to enter the village from time to time and execute the orders and Quests of building a new village" );
define( "LANGUI_GUIDE_T34", "Quest 6: Messages" );
define( "LANGUI_GUIDE_T35", "You can communicate with other players through messages, I sent a test message to you. Do read it and then return here <br> <br> Note: Do not forget, the icon of the messages contain two parts, the left-hand section of the reports and the left side of the messages" );
define( "LANGUI_GUIDE_T36", "Read the new message" );
define( "LANGUI_GUIDE_T37", "I have received the message? Very excellent" );
define( "LANGUI_GUIDE_T38", "I ll give you some gold as a gift, by the gold you can do several things, for example, extend the period of account <b><font color=\"#71D000\">P</font><font color=\"#FF6F0F\">L</font><font color=\"#71D000\">U</font><font color=\"#FF6F0F\">S</font></b> Or increase the production of your resources. To do so, click on" );
define( "LANGUI_GUIDE_T39", "Tatar war" );
define( "LANGUI_GUIDE_T40", "<font color=\"#71D000\">P</font><font color=\"#FF6F0F\">L</font><font color=\"#71D000\">U</font><font color=\"#FF6F0F\">S</font>" );
define( "LANGUI_GUIDE_T41", "In the menu on the right of the screen" );
define( "LANGUI_GUIDE_T42", "Gold" );
define( "LANGUI_GUIDE_T43", "Quest 7: Neighbor" );
define( "LANGUI_GUIDE_T44", "around you there are many villages, one of the village its name" );
define( "LANGUI_GUIDE_T45", "Click on the icon \"map\" in the top menu and look for that village. You can see the names of villages in the map passes the mouse over the villages" );
define( "LANGUI_GUIDE_T46", "Find the coordinates of the village" );
define( "LANGUI_GUIDE_T47", "and then enter it here" );
define( "LANGUI_GUIDE_T48", "the Quest" );
define( "LANGUI_GUIDE_T49", "error, this is not the correct coordinates for the village" );
define( "LANGUI_GUIDE_T50", "try again" );
define( "LANGUI_GUIDE_T51", "true, this is the correct coordinates for the village" );
define( "LANGUI_GUIDE_T52", "Now I will provide you with free resources equal to the village" );
define( "LANGUI_GUIDE_T53", "Quest 8: Army" );
define( "LANGUI_GUIDE_T54", "Now I have a special mission for you. Im hungry! Give me 200 of wheat<br><br>On the other hand I will try to arrange you to promote a huge army to protect your village" );
define( "LANGUI_GUIDE_T55", "Send 200 Of wheat to the Quest Manager" );
define( "LANGUI_GUIDE_T56", "Send wheat" );
define( "LANGUI_GUIDE_T57", "insufficient resources" );
define( "LANGUI_GUIDE_T58", "Ammmm, Delicious! Thank you for the delicious meal of wheat. Sahakq Now you and Uday huge army to protect your village. perhaps the arrival of the army will take several hours" );
define( "LANGUI_GUIDE_T59", "huge army" );
define( "LANGUI_GUIDE_T60", "Quest 9: one of each type" );
define( "LANGUI_GUIDE_T61", "for there must be something to do in the Tatar war! while you wait for the arrival of the army Develop Hattab, the clay pit, iron mine and the wheat field to level 1" );
define( "LANGUI_GUIDE_T62", "Develop additional field from each supplier of level 1" );
define( "LANGUI_GUIDE_T63", "very excellent. your production of resources began to flourish <br> <br> very soon we will be able to start construction of buildings in the village" );
define( "LANGUI_GUIDE_T64", "Mission 10: coming soon" );
define( "LANGUI_GUIDE_T65", "Now there you have some time to rest until the arrival of the huge army which I sent you. <br> <br> from now to the time of the arrival of the army you can explore the map or the development of several fields of resources" );
define( "LANGUI_GUIDE_T66", "Wait for the arrival of Army Quest Manager" );
define( "LANGUI_GUIDE_T67", "Protect,,, very strange! This is the cheapest available Army. Perhaps I should have paid better attention to that <br><br>How can I fix this error" );
define( "LANGUI_GUIDE_T68", "On account<b> <font color=\"#71D000\">p</font><font color=\"#FF6F0F\">l</font><font color=\"#FF6F0F\">us</font></b>" );
define( "LANGUI_GUIDE_T69", "Quest 11: reports" );
define( "LANGUI_GUIDE_T70", "Every time there is something important in your village report will be sent to you. You can see the reports by clicking on the <i>Right</i> Icon of letters and reports (the fifth icon from right to left). Read the new report and then return here" );
define( "LANGUI_GUIDE_T71", "read the latest reports" );
define( "LANGUI_GUIDE_T72", "Yes, absolutely. I have opened the correct report" );
define( "LANGUI_GUIDE_T73", "Quest 12: All to level 1" );
define( "LANGUI_GUIDE_T74", "Now you must develop the production of your resources a bit. Develop all resource fields to level 1" );
define( "LANGUI_GUIDE_T75", "Develop a resource for all fields of level 1" );
define( "LANGUI_GUIDE_T76", "very excellent, your production of resources has become prosperous. <br> <br> very soon we will start building the buildings in the village" );
define( "LANGUI_GUIDE_T77", "Quest 13: Dove of Peace" );
define( "LANGUI_GUIDE_T78", "In the early days of your registration in the game you are under protection from attack you by other players. To find out for your protection from attacks, add the code <b> [0#] </b> In your description. Click on the membership card and then click on edit your personal information" );
define( "LANGUI_GUIDE_T79", "Write code" );
define( "LANGUI_GUIDE_T80", "In the description in your membership card" );
define( "LANGUI_GUIDE_T81", "Well done!  Now everyone can see you re a great warrior" );
define( "LANGUI_GUIDE_T82", "Quest 14: The cache" );
define( "LANGUI_GUIDE_T83", "It is time to build a bunker as the world war Tatar dangerous world.<br><br>Many of the players live on the plunder of others, do not build a bunker to hide at least part of your resources from enemy plundering" );
define( "LANGUI_GUIDE_T84", "Build your cache" );
define( "LANGUI_GUIDE_T85", "Great work, now would be difficult for the players pillage your village Allimin<br><br>If you have been looting the villagers will hide in the bunker on their own resources" );
define( "LANGUI_GUIDE_T86", "Quest 15: to the second level" );
define( "LANGUI_GUIDE_T87", "There is always something to be done in the Tatar war! Develop Hattab, the clay pit and iron mine and a field of wheat and one of each type to the level 2" );
define( "LANGUI_GUIDE_T88", "Develop a single field from each supplier to the level 2" );
define( "LANGUI_GUIDE_T89", "great, your village began to grow and flourish" );
define( "LANGUI_GUIDE_T90", "Quest 16: Quick Guide" );
define( "LANGUI_GUIDE_T91", "in the Quick Guide you can read brief information about the types of buildings and also the different types of troops available <br> <br> Adaft on the \"Quick Guide\" in the menu on the right of the page and try to know how much the unit cost of wood to build the barracks" );
define( "LANGUI_GUIDE_T92", "Enter in the box below how many units of the wood enough to build the barracks" );
define( "LANGUI_GUIDE_T93", "No, Alzqh cost less than that" );
define( "LANGUI_GUIDE_T94", "No, the barracks of the most expensive" );
define( "LANGUI_GUIDE_T95", "Excellent! barracks building costs" );
define( "LANGUI_GUIDE_T96", "unit of wood" );
define( "LANGUI_GUIDE_T97", "Quest 17: The Main Building" );
define( "LANGUI_GUIDE_T98", "some of the important buildings in the village require that the "."C:\\Decoder\\bin\\rm\\file.php"." building at level 3 so you can build and market such as the barracks" );
define( "LANGUI_GUIDE_T99", "Develop the "."C:\\Decoder\\bin\\rm\\file.php"." building to level 3" );
define( "LANGUI_GUIDE_T100", "Excellent. was the completion of the development of the "."C:\\Decoder\\bin\\rm\\file.php"." building to level 3 <br> <br> this development can not build new types of buildings and all but you can also build in your village faster" );
define( "LANGUI_GUIDE_T101", "Quest 18: Mrtpetk" );
define( "LANGUI_GUIDE_T102", "finding your Mrtpetk in the statistics again and enjoy your progress" );
define( "LANGUI_GUIDE_T103", "No, no. you must enter your position here. order in just a number" );
define( "LANGUI_GUIDE_T104", "If you are training will be a good day to this level. try again" );
define( "LANGUI_GUIDE_T105", "You better Pkther. try again" );
define( "LANGUI_GUIDE_T106", "Excellent! This is your ranking current" );
define( "LANGUI_GUIDE_T107", "Quest 19: weapons or money" );
define( "LANGUI_GUIDE_T108", "Now we must make a decision: Either trade peacefully or become a warrior scary <br> <br> to build a market need to store grain, and to build the barracks you need to the assembly point" );
define( "LANGUI_GUIDE_T109", "trade" );
define( "LANGUI_GUIDE_T110", "army" );
define( "LANGUI_GUIDE_T111", "courageous decision, to be able to send soldiers, you need a rallying point. <br> <br> can build an assembly point, except in only one place" );
define( "LANGUI_GUIDE_T112", "building site" );
define( "LANGUI_GUIDE_T113", "assembly point is in the right hand side of the "."C:\\Decoder\\bin\\rm\\file.php"." building and a little bit down from the arch-shaped" );
define( "LANGUI_GUIDE_T114", "build your rally point" );
define( "LANGUI_GUIDE_T115", "Trade is your choice, you are in waiting times is certainly a golden" );
define( "LANGUI_GUIDE_T116", "Build a grain store" );
define( "LANGUI_GUIDE_T117", "Well done! Bbinak to the rally point you have become a possibility in the near future to launch wars" );
define( "LANGUI_GUIDE_T118", "Well done! Bbinak to store grains have become a potential to store more wheat" );
define( "LANGUI_GUIDE_T119", "Quest 20: store" );
define( "LANGUI_GUIDE_T120", "Quest 20: the barracks" );
define( "LANGUI_GUIDE_T121", "in addition to wheat storage you need to store the rest of the resources to avoid a throw surplus. build your store now" );
define( "LANGUI_GUIDE_T122", "Build your store" );
define( "LANGUI_GUIDE_T123", "Excellent! has been the construction of the store ....< br> <br> has now been completed all the requirements for the construction of the market" );
define( "LANGUI_GUIDE_T124", "You now have the "."C:\\Decoder\\bin\\rm\\file.php"." building at level 3 and a rallying point. This means that the requirements of building the barracks have been met <br> <br> in the barracks you can build troops to fight" );
define( "LANGUI_GUIDE_T125", "Build the barracks" );
define( "LANGUI_GUIDE_T126", "Well done! has been compiled from the best coaches to train their kingdom your men the best form" );
define( "LANGUI_GUIDE_T127", "Quest 21: Market" );
define( "LANGUI_GUIDE_T128", "Quest 21:! training" );
define( "LANGUI_GUIDE_T129", "Build a market to be able to trade with other players" );
define( "LANGUI_GUIDE_T130", "as well as build your market" );
define( "LANGUI_GUIDE_T131", "was the completion of building the market, now you can trade or buy resources from abroad! If you want to trade, try to produce the required resources in abundance in the market so you can profit better" );
define( "LANGUI_GUIDE_T132", "Now you have the barracks and you can start training troops. Train 2" );
define( "LANGUI_GUIDE_T133", "as well as the Train 2" );
define( "LANGUI_GUIDE_T134", "and finally finished building your great military. <br> <br> before you build the army of looting is recommended that you test" );
define( "LANGUI_GUIDE_T135", "battle simulator" );
define( "LANGUI_GUIDE_T136", "to see how the number of units required to fight a rat and one without any loss by your army" );
define( "LANGUI_GUIDE_T137", "Quest 22: All to level 2" );
define( "LANGUI_GUIDE_T138", "Now it's time to lay the foundation for your strength and how much money you! now Level 1 is not enough ... I know that it will take a long time but in the end you will find that the subject is worth it. Develop all resource fields to level 2" );
define( "LANGUI_GUIDE_T139", "Develop a resource for all fields of level 2" );
define( "LANGUI_GUIDE_T140", "Congratulations, your village grow and prosper greatly" );
define( "LANGUI_GUIDE_T141", "Quest 23: Embassy" );
define( "LANGUI_GUIDE_T142", "The world of war Tatar is dangerous. you've already built a bunker for you to provide better protection against thieves. but he prefers to organize the coalition. <br> established an embassy to be able to accept invitations from alliances" );
define( "LANGUI_GUIDE_T143", "very good, the embassy has been built" );
define( "LANGUI_GUIDE_T144", "Quest 24: Alliance" );
define( "LANGUI_GUIDE_T145", "cooperation is important in the war of the Tatars. The players are working together to organize themselves into coalitions. <br> try to get yourself to the invitation by a coalition of your surroundings and join this alliance. <br> Instead, you can also create private alliance. but for this you first need to embassy level 3 " );
define( "LANGUI_GUIDE_T146", "joined the Alliance or the Alliance has been created" );
define( "LANGUI_GUIDE_T147", "great, but without joining the alliance, it will be hard for you to be a huge empire of the piece would prefer to join the alliance has <br> <br> I have completed the last Quest for you. The population of the village to congratulate you now celebrate it. from now on I will not be there to help you and will complement the long haul on your own " );
define( "LANGUI_GUIDE_T148", "no Quests" );
define( "LANGUI_GUIDE_T149", "if they were not willing to do these Quests you can cancel the activation of Quests\r\nBut be careful, after the cancellation of missions, you will not be getting them in the field once again\r\nThe piece is well thought of and made ​​the right decision, you probably have the desire to complete the Quests in the later\r\nWhatever the decision taken by I want to make sure I give you resources and stand on your side, only if you want to piece. You know where to find me" );
define( "LANGUI_GUIDE_T150", "play missions" );
define( "LANGUI_GUIDE_T151", "abolition of the Quests" );
define( "LANGUI_GUIDE_T152", "summary of the raw materials" );
define( "LANGUI_GUIDE_T153", "supply of raw resources of your own" );
define( "LANGUI_GUIDE_T154", "supply" );
define( "LANGUI_GUIDE_T155", "time of supply" );
define( "LANGUI_GUIDE_T156", "status" );
define( "LANGUI_GUIDE_T157", "one day account" );
define( "LANGUI_GUIDE_T158", "invoke" );
define( "LANGUI_GUIDE_T159", "has" );
define( "LANGUI_GUIDE_T160", "waiting" );
define( "LANGUI_GUIDE_T161", "on account" );
define( "LANGUI_GUIDE_T162", "Build your embassy" );
?>
