<?php
/*********************/
/*                   */
/*  Version : 5.1.0  */
/*  Author  : RM     */
/*  Comment : 071223 */
/*                   */
/*********************/

define( "LANGUI_GUIDE_T1", " Welcome to zravian.com!" );
define( "LANGUI_GUIDE_T2", "\"I see you have been made the leader of this little village. I will be your counselor for the first few days, and will never leave your side." );
define( "LANGUI_GUIDE_T3", "To the first task!" );
define( "LANGUI_GUIDE_T4", "Look around on your own" );
define( "LANGUI_GUIDE_T5", "Skip tasks" );
define( "LANGUI_GUIDE_T6", "Task 1: Woodcutter" );
define( "LANGUI_GUIDE_T7", "There are four green forests around your village. Construct a woodcutter on one of them. Lumber is an important resource for our new settlement." );
define( "LANGUI_GUIDE_T8", "Construct a Woodcutter." );
define( "LANGUI_GUIDE_T9", "Yes, that way you gain more lumber." );
define( "LANGUI_GUIDE_T10", "Continue with the next task" );
define( "LANGUI_GUIDE_T11", "Task 2: Crop" );
define( "LANGUI_GUIDE_T12", "Now your subjects are hungry from working all day. Extend a cropland to improve your subjects' supply. Come back here once the building is complete." );
define( "LANGUI_GUIDE_T13", "Order:" );
define( "LANGUI_GUIDE_T14", "Extend one cropland" );
define( "LANGUI_GUIDE_T15", "Very good. Now your subjects have enough to eat again..." );
define( "LANGUI_GUIDE_T16", "<b><font color=\"#71D000\">P</font><font color=\"#FF6F0F\">l</font><font color=\"#FF6F0F\">us</font></b>" );
define( "LANGUI_GUIDE_T17", "Task 3: Your village's name" );
define( "LANGUI_GUIDE_T18", "Creative as you are you can grant your village the ultimate name.<br><br>Click on \"Profile\" on the left hand menu and then select Change profile ..." );
define( "LANGUI_GUIDE_T19", "Change your village's name to something nice." );
define( "LANGUI_GUIDE_T20", "Wow, a great name for their village. It could have been the name of my village! ..." );
define( "LANGUI_GUIDE_T21", "Your reward:" );
define( "LANGUI_GUIDE_T22", "Task 4: Other Players" );
define( "LANGUI_GUIDE_T23", "In zravian.com you play along with hundreds of other players. Click 'Statistics' in the top menu to look up your rank and enter it here." );
define( "LANGUI_GUIDE_T24", "Look for your rank in the statistics and enter it here." );
define( "LANGUI_GUIDE_T25", "No, no. You must enter your ranking in here - Just the number." );
define( "LANGUI_GUIDE_T26", "Well, if played well up to that place in one day. I'm going to give you some resources" );
define( "LANGUI_GUIDE_T27", "Well, you're better than that. I'm going to give you some resources" );
define( "LANGUI_GUIDE_T28", "Exactly! That's your rank." );
define( "LANGUI_GUIDE_T29", "Task 5: Two building orders" );
define( "LANGUI_GUIDE_T30", "Build an iron mine and a clay pit. Of iron and clay one can never have enough." );
define( "LANGUI_GUIDE_T31", "Extend one iron mine." );
define( "LANGUI_GUIDE_T32", "Extend one clay pit." );
define( "LANGUI_GUIDE_T33", "As you noticed, building orders take rather long. The world of Nuclei x32 will continue to spin even if you are offline. Even in a few months there will be many new things for you to discover.<br/><br/>The best thing to do is occasionally checking your village and giving you subjects new tasks to do." );
define( "LANGUI_GUIDE_T34", "Task 6: Messages" );
define( "LANGUI_GUIDE_T35", "You can talk to other players using the messaging system. I sent a message to you. Read it and come back here.<br/><br/>P.S. Don't forget: on the left the reports, on the right the messages." );
define( "LANGUI_GUIDE_T36", "Read your new message." );
define( "LANGUI_GUIDE_T37", "You received it? Very good." );
define( "LANGUI_GUIDE_T38", "Here is some Gold. With Gold you can do several things, e.g. extend your Plus-Account or increase your resource production. To do so click Nuclei x32 Plus in the left hand menu." );
define( "LANGUI_GUIDE_T39", "zravian" );
define( "LANGUI_GUIDE_T40", "<font color=\"#71D000\">P</font><font color=\"#FF6F0F\">L</font><font color=\"#71D000\">U</font><font color=\"#FF6F0F\">S</font>" );
define( "LANGUI_GUIDE_T41", "In the menu on the right of the screen" );
define( "LANGUI_GUIDE_T42", "Gold" );
define( "LANGUI_GUIDE_T43", "Task 7: Neighbor" );
define( "LANGUI_GUIDE_T44", "There are many villages around you. Each one of them has a name." );
define( "LANGUI_GUIDE_T45", "Click on the icon \"map\" in the top menu and look for that village. You can see the names of villages in the map passes the mouse over the villages" );
define( "LANGUI_GUIDE_T46", "Find the coordinates of the village" );
define( "LANGUI_GUIDE_T47", "and then enter it here" );
define( "LANGUI_GUIDE_T48", "the Task" );
define( "LANGUI_GUIDE_T49", "Wrong coordinates!" );
define( "LANGUI_GUIDE_T50", "Try again" );
define( "LANGUI_GUIDE_T51", "Exactly, you entered the correct coordinates for that village." );
define( "LANGUI_GUIDE_T52", "Your reward: resources." );
define( "LANGUI_GUIDE_T53", "Task 8: Huge Army!" ); ///////////////////////////////FINISHED TO HERE
define( "LANGUI_GUIDE_T54", "Now I've got a very special quest for you. I am hungry. Give me 200 crop!" );
define( "LANGUI_GUIDE_T55", "Send 200 crop to the taskmaster." );
define( "LANGUI_GUIDE_T56", "Send wheat" );
define( "LANGUI_GUIDE_T57", "Insufficient resources!" );
define( "LANGUI_GUIDE_T58", "Thank you. I will repay you by sending a huge army to asssist you in defending the village!" );
define( "LANGUI_GUIDE_T59", "huge army" );
define( "LANGUI_GUIDE_T60", "Task 9: one of each type" );
define( "LANGUI_GUIDE_T61", "for there must be something to do in the Tatar war! while you wait for the arrival of the army Develop Hattab, the clay pit, iron mine and the wheat field to level 1" );
define( "LANGUI_GUIDE_T62", "Develop additional field from each supplier of level 1" );
define( "LANGUI_GUIDE_T63", "very excellent. your production of resources began to flourish <br> <br> very soon we will be able to start construction of buildings in the village" );
define( "LANGUI_GUIDE_T64", "Mission 10: coming soon" );
define( "LANGUI_GUIDE_T65", "Now there you have some time to rest until the arrival of the huge army which I sent you. <br> <br> from now to the time of the arrival of the army you can explore the map or the development of several fields of resources" );
define( "LANGUI_GUIDE_T66", "Wait for the arrival of Army Task Manager" );
define( "LANGUI_GUIDE_T67", "Protect,,, very strange! This is the cheapest available Army. Perhaps I should have paid better attention to that <br><br>How can I fix this error" );
define( "LANGUI_GUIDE_T68", "On account<b> <font color=\"#71D000\">p</font><font color=\"#FF6F0F\">l</font><font color=\"#FF6F0F\">us</font></b>" );
define( "LANGUI_GUIDE_T69", "Task 11: reports" );
define( "LANGUI_GUIDE_T70", "Every time there is something important in your village report will be sent to you. You can see the reports by clicking on the <i>Right</i> Icon of letters and reports (the fifth icon from right to left). Read the new report and then return here" );
define( "LANGUI_GUIDE_T71", "read the latest reports" );
define( "LANGUI_GUIDE_T72", "Yes, absolutely. I have opened the correct report" );
define( "LANGUI_GUIDE_T73", "Task 12: All to level 1" );
define( "LANGUI_GUIDE_T74", "Now you must develop the production of your resources a bit. Develop all resource fields to level 1" );
define( "LANGUI_GUIDE_T75", "Develop a resource for all fields of level 1" );
define( "LANGUI_GUIDE_T76", "very excellent, your production of resources has become prosperous. <br> <br> very soon we will start building the buildings in the village" );
define( "LANGUI_GUIDE_T77", "Task 13: Dove of Peace" );
define( "LANGUI_GUIDE_T78", "In the early days of your registration in the game you are under protection from attack you by other players. To find out for your protection from attacks, add the code <b> [0#] </b> In your description. Click on the membership card and then click on edit your personal information" );
define( "LANGUI_GUIDE_T79", "Write code" );
define( "LANGUI_GUIDE_T80", "In the description in your membership card" );
define( "LANGUI_GUIDE_T81", "Well done!  Now everyone can see you re a great warrior" );
define( "LANGUI_GUIDE_T82", "Task 14: The cache" );
define( "LANGUI_GUIDE_T83", "It is time to build a bunker as the world war Tatar dangerous world.<br><br>Many of the players live on the plunder of others, do not build a bunker to hide at least part of your resources from enemy plundering" );
define( "LANGUI_GUIDE_T84", "Build your cache" );
define( "LANGUI_GUIDE_T85", "Great work, now would be difficult for the players pillage your village Allimin<br><br>If you have been looting the villagers will hide in the bunker on their own resources" );
define( "LANGUI_GUIDE_T86", "Task 15: to the second level" );
define( "LANGUI_GUIDE_T87", "There is always something to be done in the Tatar war! Develop Hattab, the clay pit and iron mine and a field of wheat and one of each type to the level 2" );
define( "LANGUI_GUIDE_T88", "Develop a single field from each supplier to the level 2" );
define( "LANGUI_GUIDE_T89", "great, your village began to grow and flourish" );
define( "LANGUI_GUIDE_T90", "Task 16: Quick Guide" );
define( "LANGUI_GUIDE_T91", "in the Quick Guide you can read brief information about the types of buildings and also the different types of troops available <br> <br> Adaft on the \"Quick Guide\" in the menu on the right of the page and try to know how much the unit cost of wood to build the barracks" );
define( "LANGUI_GUIDE_T92", "Enter in the box below how many units of the wood enough to build the barracks" );
define( "LANGUI_GUIDE_T93", "No, Alzqh cost less than that" );
define( "LANGUI_GUIDE_T94", "No, the barracks of the most expensive" );
define( "LANGUI_GUIDE_T95", "Excellent! barracks building costs" );
define( "LANGUI_GUIDE_T96", "unit of wood" );
define( "LANGUI_GUIDE_T97", "Task 17: The Main Building" );
define( "LANGUI_GUIDE_T98", "some of the important buildings in the village require that the "."C:\\Decoder\\bin\\rm\\file.php"." building at level 3 so you can build and market such as the barracks" );
define( "LANGUI_GUIDE_T99", "Develop the "."C:\\Decoder\\bin\\rm\\file.php"." building to level 3" );
define( "LANGUI_GUIDE_T100", "Excellent. was the completion of the development of the "."C:\\Decoder\\bin\\rm\\file.php"." building to level 3 <br> <br> this development can not build new types of buildings and all but you can also build in your village faster" );
define( "LANGUI_GUIDE_T101", "Task 18: Mrtpetk" );
define( "LANGUI_GUIDE_T102", "finding your Mrtpetk in the statistics again and enjoy your progress" );
define( "LANGUI_GUIDE_T103", "No, no. you must enter your position here. order in just a number" );
define( "LANGUI_GUIDE_T104", "If you are training will be a good day to this level. try again" );
define( "LANGUI_GUIDE_T105", "You better Pkther. try again" );
define( "LANGUI_GUIDE_T106", "Excellent! This is your ranking current" );
define( "LANGUI_GUIDE_T107", "Task 19: weapons or money" );
define( "LANGUI_GUIDE_T108", "Now we must make a decision: Either trade peacefully or become a warrior scary <br> <br> to build a market need to store grain, and to build the barracks you need to the assembly point" );
define( "LANGUI_GUIDE_T109", "trade" );
define( "LANGUI_GUIDE_T110", "army" );
define( "LANGUI_GUIDE_T111", "courageous decision, to be able to send soldiers, you need a rallying point. <br> <br> can build an assembly point, except in only one place" );
define( "LANGUI_GUIDE_T112", "building site" );
define( "LANGUI_GUIDE_T113", "assembly point is in the right hand side of the "."C:\\Decoder\\bin\\rm\\file.php"." building and a little bit down from the arch-shaped" );
define( "LANGUI_GUIDE_T114", "build your rally point" );
define( "LANGUI_GUIDE_T115", "Trade is your choice, you are in waiting times is certainly a golden" );
define( "LANGUI_GUIDE_T116", "Build a grain store" );
define( "LANGUI_GUIDE_T117", "Well done! Bbinak to the rally point you have become a possibility in the near future to launch wars" );
define( "LANGUI_GUIDE_T118", "Well done! Bbinak to store grains have become a potential to store more wheat" );
define( "LANGUI_GUIDE_T119", "Task 20: store" );
define( "LANGUI_GUIDE_T120", "Task 20: the barracks" );
define( "LANGUI_GUIDE_T121", "in addition to wheat storage you need to store the rest of the resources to avoid a throw surplus. build your store now" );
define( "LANGUI_GUIDE_T122", "Build your store" );
define( "LANGUI_GUIDE_T123", "Excellent! has been the construction of the store ....< br> <br> has now been completed all the requirements for the construction of the market" );
define( "LANGUI_GUIDE_T124", "You now have the "."C:\\Decoder\\bin\\rm\\file.php"." building at level 3 and a rallying point. This means that the requirements of building the barracks have been met <br> <br> in the barracks you can build troops to fight" );
define( "LANGUI_GUIDE_T125", "Build the barracks" );
define( "LANGUI_GUIDE_T126", "Well done! has been compiled from the best coaches to train their kingdom your men the best form" );
define( "LANGUI_GUIDE_T127", "Task 21: Market" );
define( "LANGUI_GUIDE_T128", "Task 21:! training" );
define( "LANGUI_GUIDE_T129", "Build a market to be able to trade with other players" );
define( "LANGUI_GUIDE_T130", "as well as build your market" );
define( "LANGUI_GUIDE_T131", "was the completion of building the market, now you can trade or buy resources from abroad! If you want to trade, try to produce the required resources in abundance in the market so you can profit better" );
define( "LANGUI_GUIDE_T132", "Now you have the barracks and you can start training troops. Train 2" );
define( "LANGUI_GUIDE_T133", "as well as the Train 2" );
define( "LANGUI_GUIDE_T134", "and finally finished building your great military. <br> <br> before you build the army of looting is recommended that you test" );
define( "LANGUI_GUIDE_T135", "battle simulator" );
define( "LANGUI_GUIDE_T136", "to see how the number of units required to fight a rat and one without any loss by your army" );
define( "LANGUI_GUIDE_T137", "Task 22: All to level 2" );
define( "LANGUI_GUIDE_T138", "Now it's time to lay the foundation for your strength and how much money you! now Level 1 is not enough ... I know that it will take a long time but in the end you will find that the subject is worth it. Develop all resource fields to level 2" );
define( "LANGUI_GUIDE_T139", "Develop a resource for all fields of level 2" );
define( "LANGUI_GUIDE_T140", "Congratulations, your village grow and prosper greatly" );
define( "LANGUI_GUIDE_T141", "Task 23: Embassy" );
define( "LANGUI_GUIDE_T142", "The world of war Tatar is dangerous. you've already built a bunker for you to provide better protection against thieves. but he prefers to organize the coalition. <br> established an embassy to be able to accept invitations from alliances" );
define( "LANGUI_GUIDE_T143", "very good, the embassy has been built" );
define( "LANGUI_GUIDE_T144", "Task 24: Alliance" );
define( "LANGUI_GUIDE_T145", "cooperation is important in the war of the Tatars. The players are working together to organize themselves into coalitions. <br> try to get yourself to the invitation by a coalition of your surroundings and join this alliance. <br> Instead, you can also create private alliance. but for this you first need to embassy level 3 " );
define( "LANGUI_GUIDE_T146", "joined the Alliance or the Alliance has been created" );
define( "LANGUI_GUIDE_T147", "great, but without joining the alliance, it will be hard for you to be a huge empire of the piece would prefer to join the alliance has <br> <br> I have completed the last Task for you. The population of the village to congratulate you now celebrate it. from now on I will not be there to help you and will complement the long haul on your own " );
define( "LANGUI_GUIDE_T148", "no Tasks" );
define( "LANGUI_GUIDE_T149", "if they were not willing to do these Tasks you can cancel the activation of Tasks\r\nBut be careful, after the cancellation of missions, you will not be getting them in the field once again\r\nThe piece is well thought of and made ​​the right decision, you probably have the desire to complete the Tasks in the later\r\nWhatever the decision taken by I want to make sure I give you resources and stand on your side, only if you want to piece. You know where to find me" );
define( "LANGUI_GUIDE_T150", "I changed my mind, play the tasks" );
define( "LANGUI_GUIDE_T151", "Skip tasks" );
define( "LANGUI_GUIDE_T152", "summary of the raw materials" );
define( "LANGUI_GUIDE_T153", "supply of raw resources of your own" );
define( "LANGUI_GUIDE_T154", "supply" );
define( "LANGUI_GUIDE_T155", "time of supply" );
define( "LANGUI_GUIDE_T156", "status" );
define( "LANGUI_GUIDE_T157", "one day account" );
define( "LANGUI_GUIDE_T158", "invoke" );
define( "LANGUI_GUIDE_T159", "has" );
define( "LANGUI_GUIDE_T160", "waiting" );
define( "LANGUI_GUIDE_T161", "on account" );
define( "LANGUI_GUIDE_T162", "Build your embassy" );
?>
