<?php
/*********************/
/*                   */
/*  Version : 5.1.0  */
/*  Author  : RM     */
/*  Comment : 071223 */
/*                   */
/*********************/

define( "LANGUI_GUIDE_T1", " Welcome to zravian.com!" );
define( "LANGUI_GUIDE_T2", "\"I see you have been made the leader of this little village. I will be your counselor for the first few days, and will never leave your side." );
define( "LANGUI_GUIDE_T3", "To the first task!" );
define( "LANGUI_GUIDE_T4", "Look around on your own" );
define( "LANGUI_GUIDE_T5", "Skip tasks" );
define( "LANGUI_GUIDE_T6", "Task 1: Woodcutter" );
define( "LANGUI_GUIDE_T7", "There are four green forests around your village. Construct a woodcutter on one of them. Lumber is an important resource for our new settlement." );
define( "LANGUI_GUIDE_T8", "Construct a Woodcutter." );
define( "LANGUI_GUIDE_T9", "Yes, that way you gain more lumber." );
define( "LANGUI_GUIDE_T10", "Continue with the next task" );
define( "LANGUI_GUIDE_T11", "Task 2: Crop" );
define( "LANGUI_GUIDE_T12", "Now your subjects are hungry from working all day. Extend a cropland to improve your subjects' supply. Come back here once the building is complete." );
define( "LANGUI_GUIDE_T13", "Order:" );
define( "LANGUI_GUIDE_T14", "Extend one cropland" );
define( "LANGUI_GUIDE_T15", "Very good. Now your subjects have enough to eat again..." );
define( "LANGUI_GUIDE_T16", "<b><font color=\"#71D000\">P</font><font color=\"#FF6F0F\">l</font><font color=\"#FF6F0F\">us</font></b>" );
define( "LANGUI_GUIDE_T17", "Task 3: Your village's name" );
define( "LANGUI_GUIDE_T18", "Creative as you are you can grant your village the ultimate name.<br><br>Click on \"Profile\" on the left hand menu and then select Change profile ..." );
define( "LANGUI_GUIDE_T19", "Change your village's name to something nice." );
define( "LANGUI_GUIDE_T20", "Wow, a great name for their village. It could have been the name of my village! ..." );
define( "LANGUI_GUIDE_T21", "Your reward:" );
define( "LANGUI_GUIDE_T22", "Task 4: Other Players" );
define( "LANGUI_GUIDE_T23", "In zravian.com you play along with hundreds of other players. Click 'Statistics' in the top menu to look up your rank and enter it here." );
define( "LANGUI_GUIDE_T24", "Look for your rank in the statistics and enter it here." );
define( "LANGUI_GUIDE_T25", "No, no. You must enter your ranking in here - Just the number." );
define( "LANGUI_GUIDE_T26", "Well, if played well up to that place in one day. I'm going to give you some resources" );
define( "LANGUI_GUIDE_T27", "Well, you're better than that. I'm going to give you some resources" );
define( "LANGUI_GUIDE_T28", "Exactly! That's your rank." );
define( "LANGUI_GUIDE_T29", "Task 5: Two building orders" );
define( "LANGUI_GUIDE_T30", "Build an iron mine and a clay pit. Of iron and clay one can never have enough." );
define( "LANGUI_GUIDE_T31", "Extend one iron mine." );
define( "LANGUI_GUIDE_T32", "Extend one clay pit." );
define( "LANGUI_GUIDE_T33", "As you noticed, building orders take rather long. The world of Nuclei x32 will continue to spin even if you are offline. Even in a few months there will be many new things for you to discover.<br/><br/>The best thing to do is occasionally checking your village and giving you subjects new tasks to do." );
define( "LANGUI_GUIDE_T34", "Task 6: Messages" );
define( "LANGUI_GUIDE_T35", "You can talk to other players using the messaging system. I sent a message to you. Read it and come back here.<br/><br/>P.S. Don't forget: on the left the reports, on the right the messages." );
define( "LANGUI_GUIDE_T36", "Read your new message." );
define( "LANGUI_GUIDE_T37", "You received it? Very good." );
define( "LANGUI_GUIDE_T38", "Here is some Gold. With Gold you can do several things, e.g. extend your Plus-Account or increase your resource production. To do so click Nuclei x32 Plus in the left hand menu." );
define( "LANGUI_GUIDE_T39", "zravian" );
define( "LANGUI_GUIDE_T40", "<font color=\"#71D000\">P</font><font color=\"#FF6F0F\">L</font><font color=\"#71D000\">U</font><font color=\"#FF6F0F\">S</font>" );
define( "LANGUI_GUIDE_T41", "In the menu on the right of the screen" );
define( "LANGUI_GUIDE_T42", "Gold" );
define( "LANGUI_GUIDE_T43", "Task 7: Neighbor" );
define( "LANGUI_GUIDE_T44", "There are many villages around you. Each one of them has a name." );
define( "LANGUI_GUIDE_T45", "Click on the icon \"map\" in the top menu and look for that village. You can see the names of villages in the map passes the mouse over the villages" );
define( "LANGUI_GUIDE_T46", "Find the coordinates of the village" );
define( "LANGUI_GUIDE_T47", "and then enter it here" );
define( "LANGUI_GUIDE_T48", "the Task" );
define( "LANGUI_GUIDE_T49", "Wrong coordinates!" );
define( "LANGUI_GUIDE_T50", "Try again" );
define( "LANGUI_GUIDE_T51", "Exactly, you entered the correct coordinates for that village." );
define( "LANGUI_GUIDE_T52", "Your reward: resources." );
define( "LANGUI_GUIDE_T53", "Task 8: Huge Army!" );
define( "LANGUI_GUIDE_T54", "Now I've got a very special quest for you. I am hungry. Give me 200 crop!" );
define( "LANGUI_GUIDE_T55", "Send 200 crop to the taskmaster." );
define( "LANGUI_GUIDE_T56", "Send wheat" );
define( "LANGUI_GUIDE_T57", "Insufficient resources!" );
define( "LANGUI_GUIDE_T58", "Thank you. I will repay you by sending a huge army to asssist you in defending the village!" );
define( "LANGUI_GUIDE_T59", "Huge army" );
define( "LANGUI_GUIDE_T60", "Task 9: One each" );
define( "LANGUI_GUIDE_T61", "In Travian there is always something to do! While you are waiting for your new army, extend one additional Woodcutter, Clay Pit, Iron Mine and Wheat Field to level 1" );
define( "LANGUI_GUIDE_T62", "Extend one more resource tile each to level 1." );
define( "LANGUI_GUIDE_T63", "Very good, your resource production is thriving now.<br><br>Soon we can start to construct buildings in the village." );
define( "LANGUI_GUIDE_T64", "Mission 10: coming soon" );
define( "LANGUI_GUIDE_T65", "Now there is time for a small break until the gigantic army I sent you arrives.<br>Until then you can explore the map or extend a few resource tiles." );
define( "LANGUI_GUIDE_T66", "Wait for the arrival of Army Task Manager" );
define( "LANGUI_GUIDE_T67", "Hm. Strange, that was the cheapest army to be found. Maybe I should have paid more attention to the small print...<br><br>How can I right that wrong..." );
define( "LANGUI_GUIDE_T68", "2 days <b> <font color=\"#71D000\">p</font><font color=\"#FF6F0F\">l</font><font color=\"#FF6F0F\">us</font></b>" );
define( "LANGUI_GUIDE_T69", "Task 11: Reports" );
define( "LANGUI_GUIDE_T70", "Every time something important happens to your account you will receive a report. You can see these by clicking on the left half of the 5th button (from left to right). Read the report and come back here." );
define( "LANGUI_GUIDE_T71", "Read your latest report" );
define( "LANGUI_GUIDE_T72", "Yes, exactly. This was the correct report!" );
define( "LANGUI_GUIDE_T73", "Task 12: Everything to 1" );
define( "LANGUI_GUIDE_T74", "Now we should increase your resource production a bit. Extend all your resource tiles to level 1." );
define( "LANGUI_GUIDE_T75", "Extend all resource tiles to level 1" );
define( "LANGUI_GUIDE_T76", "Very good, your resource production is thriving.<br><br>Soon we can start with constructing buildings in the village." );
define( "LANGUI_GUIDE_T77", "Task 13: Peace!" );
define( "LANGUI_GUIDE_T78", "Beginner's protection from attacks by your fellow players. You can see how long this protection lasts by adding the code [#0] to your profile." );
define( "LANGUI_GUIDE_T79", "Write the code" );
define( "LANGUI_GUIDE_T80", "into your profile" );
define( "LANGUI_GUIDE_T81", "Well done! Now everyone can see what a great warrior you are." );
define( "LANGUI_GUIDE_T82", "Task 14: Build a Cranny" );
define( "LANGUI_GUIDE_T83", "It's time to build a cranny. The world of Zravian is a dangerous place.<br><br>" );
define( "LANGUI_GUIDE_T84", "Many players survive by stealing other players' resources. Build a Cranny to hide and protect at least part of your resources from enemy attacks." );
define( "LANGUI_GUIDE_T85", "Well done, now it will be much harder for your fellow players to plunder your village.<br><br>If under attack, your villagers will hide the resources in the Cranny all on their own. Please be aware that teutons can steal more resources from a cranny than any other tribe. Gauls on the other hand have bigger crannies that hide more resources than the other tribes!" );
define( "LANGUI_GUIDE_T86", "Task 15: To Two" );
define( "LANGUI_GUIDE_T87", "In Travian there is always something to do! Extend one woodcutter, one clay pit, one iron mine and one cropland to level 2 each." );
define( "LANGUI_GUIDE_T88", "Extend one of each resource tile to level 2" );
define( "LANGUI_GUIDE_T89", "Great!" );
define( "LANGUI_GUIDE_T90", "Task 16: Manual" );
define( "LANGUI_GUIDE_T91", "In the In-game Manual you can find short information texts about different buildings and types of units. Click 'Instructions' on the left and look up how much wood the Barracks cost." );
define( "LANGUI_GUIDE_T92", "Enter how much wood the Barracks cost." );
define( "LANGUI_GUIDE_T93", "No, the barracks cost less than that." );
define( "LANGUI_GUIDE_T94", "No, the barracks cost more than that." );
define( "LANGUI_GUIDE_T95", "Excellent! Barracks cost" );
define( "LANGUI_GUIDE_T96", "wood" );
define( "LANGUI_GUIDE_T97", "Task 17: Main Building" );
define( "LANGUI_GUIDE_T98", "Your master builders need a Main Building level 3 to construct important buildings such as the Marketplace and Barracks" );
define( "LANGUI_GUIDE_T99", "Upgrade your Main Building to level 3." );
define( "LANGUI_GUIDE_T100", "Well done. The Main Building level 3 has been completed.<br><br>With this upgrade, your master builders cannot only construct more types of buildings, but will also do so faster." );
define( "LANGUI_GUIDE_T101", "Task 18: Advanced" );
define( "LANGUI_GUIDE_T102", "Look up your rank in the player statistics again and enjoy your progress.");
define( "LANGUI_GUIDE_T103", "No, no ... You must enter your current rank here." );
define( "LANGUI_GUIDE_T104", "If you're good, it won't take long to reach that. Try again." );
define( "LANGUI_GUIDE_T105", "You're better than that. Try again." );
define( "LANGUI_GUIDE_T106", "Well done! That's your current rank." );
define( "LANGUI_GUIDE_T107", "Task 19: Weapons or Economy" );
define( "LANGUI_GUIDE_T108", "Now we must make a decision: To trade peacefully or to become a scary warrior?" );
define( "LANGUI_GUIDE_T109", "Economy" );
define( "LANGUI_GUIDE_T110", "Army" );
define( "LANGUI_GUIDE_T111", "A brave decision. To be able to send troops, you need a Rally Point.<br><br>The Rally Point can only be built on a specific building site. The building site is located on the right side of the Main Building, slightly below it. The building site itself is curved in shape." );
define( "LANGUI_GUIDE_T112", "" );
define( "LANGUI_GUIDE_T113", "" );
define( "LANGUI_GUIDE_T114", "Build a Rally Point" );
define( "LANGUI_GUIDE_T115", "Trade & Economy was your choice. Golden times await you for sure!" );
define( "LANGUI_GUIDE_T116", "Build a Granary" );
define( "LANGUI_GUIDE_T117", "Your Rally Point has been constructed! A good move towards world domination!" );
define( "LANGUI_GUIDE_T118", "Well done! With the Granary you can store more wheat." );
define( "LANGUI_GUIDE_T119", "Task 20: Warehouse" );
define( "LANGUI_GUIDE_T120", "Task 20: Barracks" );
define( "LANGUI_GUIDE_T121", "Not only wheat has to be saved. Other resources can go to waste as well if they are not stored correctly." );
define( "LANGUI_GUIDE_T122", "Construct a warehouse." );
define( "LANGUI_GUIDE_T123", "Well done, your Warehouse is complete...<br><br>Now you have fulfilled all prerequisites required to construct a Marketplace." );
define( "LANGUI_GUIDE_T124", "Now you have a Main Building level 3 and a Rally Point. That means that all prerequisites for building a Barracks have been fulfilled.<br><br>In the Barracks you can train troops for fighting." );
define( "LANGUI_GUIDE_T125", "Construct the Barracks." );
define( "LANGUI_GUIDE_T126", "Well done... The best instructors from the entire country have been gathered to train your men to fight in top form." );
define( "LANGUI_GUIDE_T127", "Task 21: Market" );
define( "LANGUI_GUIDE_T128", "Task 21: Train!" );
define( "LANGUI_GUIDE_T129", "Construct a Marketplace so you can trade with your fellow players." );
define( "LANGUI_GUIDE_T130", "Construct a Marketplace" );
define( "LANGUI_GUIDE_T131", "The Marketplace has been completed. Now you can make offers of your own and accept foreign offers! When creating your own offers, you should think about offering what other players need most to get more profit." );
define( "LANGUI_GUIDE_T132", "Now that you have a Barracks, you can start training troops. Train 2 " );
define( "LANGUI_GUIDE_T133", "Train 2" );
define( "LANGUI_GUIDE_T134", "The foundation for your glorious army has been laid. Before seeing your army off to plunder, you should check the" );
define( "LANGUI_GUIDE_T135", "Combat simulator" );
define( "LANGUI_GUIDE_T136", "to see how many troops you need to successfully fight enemy units." );
define( "LANGUI_GUIDE_T137", "Task 22: Everything to 2" );
define( "LANGUI_GUIDE_T138", "Now it's time again to extend the cornerstones of might and wealth! This time level 1 is not enough... it will take a while, but in the end it will be worth it. Extend all your resource tiles to level 2!" );
define( "LANGUI_GUIDE_T139", "Extend all your resource tiles to level 2!" );
define( "LANGUI_GUIDE_T140", "Congratulations! Your village grows and thrives..." );
define( "LANGUI_GUIDE_T141", "Task 23: Embassy" );
define( "LANGUI_GUIDE_T142", "The world of Travian is dangerous. You already built a cranny to protect you against attackers. A good alliance will give you even better protection. To accept invitations from alliances, build an embassy." );
define( "LANGUI_GUIDE_T143", "Well done, the construction of your embassy is finished." );
define( "LANGUI_GUIDE_T144", "Task 24: Alliance" );
define( "LANGUI_GUIDE_T145", "Teamwork is important in Travian. Players who work together organise themselves in alliances.<br>Get an invitation from an alliance in your region and join this alliance.<br>Alternatively you can found your own alliance. For this you need an embassy level 3." );
define( "LANGUI_GUIDE_T146", "Join an alliance or found your own alliance." );
define( "LANGUI_GUIDE_T147", "Fantastic. Without an alliance it is nearly impossible to survive in Travian. It is important to be in a good alliance.<br><br>You finished your last quest and to congratulate you, the citizens of Travian are holding a feast in your honour. Now you have to continue on your own.<br><br>As a parting present I will give you some gold for you to spend at your leisure. You can use it to increase your production or extend your Plus Account. Have fun with it!" );
define( "LANGUI_GUIDE_T148", "No Tasks" );
define( "LANGUI_GUIDE_T149", "If you don't want to do the tasks, you can skip them. This is only recommended if you really know what you're doing. You will receive resources like you would with tasks.<br>At this point, you can still change your ming." );
define( "LANGUI_GUIDE_T150", "I changed my mind, play the tasks" );
define( "LANGUI_GUIDE_T151", "Skip tasks" );
define( "LANGUI_GUIDE_T152", "Summary of the raw materials" );
define( "LANGUI_GUIDE_T153", "Supply of raw resources of your own" );
define( "LANGUI_GUIDE_T154", "Supply" );
define( "LANGUI_GUIDE_T155", "Time of supply" );
define( "LANGUI_GUIDE_T156", "Status" );
define( "LANGUI_GUIDE_T157", "one day account" );
define( "LANGUI_GUIDE_T158", "invoke" );
define( "LANGUI_GUIDE_T159", "has" );
define( "LANGUI_GUIDE_T160", "waiting" );
define( "LANGUI_GUIDE_T161", "on account" );
define( "LANGUI_GUIDE_T162", "Build your embassy" );
?>
