<?php
/*********************/
/*                   */
/*  Version : 5.1.0  */
/*  Author  : RM     */
/*  Comment : 071223 */
/*                   */
/*********************/

define( "LANGUI_MANUAL_T1", "tribes" );
define( "LANGUI_MANUAL_T2", "buildings" );
define( "LANGUI_MANUAL_T3", "FAQ" );
define( "LANGUI_MANUAL_T4", "There are several people: the tribe wasp, Arabs, Romans, Gauls and Teutons. every people has its merits and disadvantages of. and even types of units differ from each other clearly. It is therefore important that you choose at the beginning of the game the people that works for you" );
define( "LANGUI_MANUAL_T5", "wasp tribe is the most offensive of all. fighters feared for their brutality in the attack. They are reneging on countries without fear of death." );
define( "LANGUI_MANUAL_T6", "forces wasp" );
define( "LANGUI_MANUAL_T7", "Offensive" );
define( "LANGUI_MANUAL_T8", "defense capability against infantry" );
define( "LANGUI_MANUAL_T9", "Defense against cavalry" );
define( "LANGUI_MANUAL_T10", "speed" );
define( "LANGUI_MANUAL_T11", "field / h" );
define( "LANGUI_MANUAL_T12", "special cases" );
define( "LANGUI_MANUAL_T13", "looting bonus: the cranny of competitors modifies only" );
define( "LANGUI_MANUAL_T14", "Simultaneous construction of resource fields and buildings" );
define( "LANGUI_MANUAL_T15", "rise through the defense wall of the city" );
define( "LANGUI_MANUAL_T16", "Merchants can carry" );
define( "LANGUI_MANUAL_T17", "very strong infantry and cavalry are strong" );
define( "LANGUI_MANUAL_T18", "Development is expensive and long" );
define( "LANGUI_MANUAL_T19", "raw materials" );
define( "LANGUI_MANUAL_T20", "fields / hour" );
define( "LANGUI_MANUAL_T21", "the Arab Empire is the Arab people from more nations that have contributed to the prosperity and development of human Baalovernma and civilizations. and the advantage of Arab fighters with tremendous force, endurance and patience in the worst of circumstances, it is one of the oldest fighters in history. have emerged and flourished the Arabic language in the country Persian Gulf, the form of tribes living in the desert, making the Arabs of the fiercest fighters, the familiarity and ability to fight wars in the harsh climatic conditions. contributed to the Islamic religion spread of the Arabic language, and has had a major role in the spread of the Arabic language with the boundaries of the Islamic empire " );
define( "LANGUI_MANUAL_T22", "the Arab forces" );
define( "LANGUI_MANUAL_T23", "Empire is the Romanian for beginners in the Tatar war. because of the high social and technological development the Romans are masters of coordination in the architecture, and soldiers belonging to the elite in the Tatar war. <br>\r\nThey are useful and relatively balanced in attack and defense. In order to ensure this diversity, they go through a lengthy and costly training. Their infantry is a living legend, but the strength of defense against enemy cavalry is clearly compared to other tribes. <br>\r\nFor beginners and those who do not know exactly what they want, the Romans are ideal for them " );
define( "LANGUI_MANUAL_T24", "Roman troops" );
define( "LANGUI_MANUAL_T25", "Very powerful infantry, average cavalry" );
define( "LANGUI_MANUAL_T27", "people of the Greek is the peaceful people of all nations. units are trained for the defense, but lower than other peoples in the attack. Greek is the knight who was born, horses legendary because of its speed, which surprise the enemy quickly third parties who are willing. <br> <br>\r\nThis tribe is relatively easy to defend, Kmaan play an aggressive investigation. It provides the possibility to develop into any strategic direction (defensive or aggressive, help in emergencies, dealers or beggars, infantry or cavalry, settler or conqueror), but some technical Aazemk. However, you can also play a tribe for beginners! " );
define( "LANGUI_MANUAL_T28", "forces the Greeks" );
define( "LANGUI_MANUAL_T29", "Speed ​​bonus: Fastest units in the game" );
define( "LANGUI_MANUAL_T30", "medium defense bonus fence" );
define( "LANGUI_MANUAL_T31", "cache two sizes larger than the rest" );
define( "LANGUI_MANUAL_T32", "cost of the war machine" );
define( "LANGUI_MANUAL_T33", "Cheap settlers" );
define( "LANGUI_MANUAL_T34", "Germanic people is the most offensive of all. fighters are notorious and feared because of the barbarity of the attack. They are reneging on countries without fear of death. <br> <br>\r\nHowever, they lack the military discipline of the Romans and Greeks, and so is their weaknesses in speed and defense. The attacker, the Teutons Professional is well suited! " );
define( "LANGUI_MANUAL_T35", "The Teutonic Troops" );
define( "LANGUI_MANUAL_T37", "The earth wall is almost indestructible, but the protection is weak" );
define( "LANGUI_MANUAL_T38", "Very cheap, and can be produced quickly and valid for looting" );
define( "LANGUI_MANUAL_T39", "weakness in the defense" );
define( "LANGUI_MANUAL_T40", "<p> at the beginning of the game you have to adopt economic fundamentals are strong. In order to achieve this must be the 18 field with respect to raw resources of the village. There are four types of resources: loggers and the drilling mud and iron mines and wheat fields. If you want to know more about them and how to develop what you need to click on the field. </ p>\r\n<p> and after some time become important for some of the buildings within the village. In order to construct Click on the link below to explain the type of green building. <br> <br> </ P>\r\n<p> should be noted that some buildings do not appear only in the advanced stage of development and construction until the completion of the conditions that might be in the development of a building or other buildings to a certain level </ p> " );
define( "LANGUI_MANUAL_T41", "Main Building" );
define( "LANGUI_MANUAL_T42", "construction workers live in the "."C:\\Decoder\\bin\\rm\\file.php"." building. the higher the level of the "."C:\\Decoder\\bin\\rm\\file.php"." building, the greater the speed of construction of buildings or development" );
define( "LANGUI_MANUAL_T43", "benefits of tribal" );
define( "LANGUI_MANUAL_T44", "the Romans: you can build or develop a building at the same time, which is developing a building or resource field" );
define( "LANGUI_MANUAL_T45", "<b> costs </ b> and <b> construction time </ b> at level 1" );
define( "LANGUI_MANUAL_T46", "conditions" );
define( "LANGUI_MANUAL_T47", "Nothing" );
define( "LANGUI_MANUAL_T48", "store" );
define( "LANGUI_MANUAL_T49", "is stored in wood, clay and iron, which is produced in the store. the higher the level of the store increased storage capacity" );
define( "LANGUI_MANUAL_T50", "Granary" );
define( "LANGUI_MANUAL_T51", "are stored wheat that is produced in a ranch in the granary. The higher the level of stored grain have increased the amount of grain that is stored" );
define( "LANGUI_MANUAL_T52", "cache" );
define( "LANGUI_MANUAL_T53", "in case of attack on the village, residents are concealing part of the raw materials automatically in hiding so as not to be stolen. At level 1 you can protect 100 of each type of raw materials from the pillaging" );
define( "LANGUI_MANUAL_T54", "Greeks: the cache can accommodate twice the amount" );
define( "LANGUI_MANUAL_T55", "Teutons: Enemy crannies only 66% of his strength in front of them" );
define( "LANGUI_MANUAL_T56", "Embassy" );
define( "LANGUI_MANUAL_T57", "in order to be able to join an alliance you need an embassy. starting from level 3 you can also create your own alliance. At each stage increases the maximum size of three members of the Alliance" );
define( "LANGUI_MANUAL_T58", "assembly point" );
define( "LANGUI_MANUAL_T59", "At the rally point you can give instructions to your troops and see the movements of troops coming to you and the sender. The rally point can only be built on one site which is in the middle of the village to the right a bit. The higher the level the more targets are available catapults" );
define( "LANGUI_MANUAL_T60", "market" );
define( "LANGUI_MANUAL_T61", "by Bmoardek market you can trade with others. The higher the level the market has increased the amount of resources that can be traded" );
define( "LANGUI_MANUAL_T64", "barracks" );
define( "LANGUI_MANUAL_T65", "in the barracks infantry can be trained. The higher the level of the barracks, the faster the training of forces" );
define( "LANGUI_MANUAL_T66", "stable" );
define( "LANGUI_MANUAL_T67", "In the Stable cavalry is trained. The higher the level the more stable speed train" );
define( "LANGUI_MANUAL_T68", "POF" );
define( "LANGUI_MANUAL_T69", "war in the factories can be built catapults and catapults. the higher the level of factories increased production speed" );
define( "LANGUI_MANUAL_T70", "academic" );
define( "LANGUI_MANUAL_T71", "In the Academy you can train new types of troops. the higher the level of increased academy types of forces that can be trained" );
define( "LANGUI_MANUAL_T72", "mourning" );
define( "LANGUI_MANUAL_T73", "Blacksmith you can develop weapons of combatants and strengthened. and when you increase the level of mourning you can request the development of better weapons" );
define( "LANGUI_MANUAL_T74", "armory" );
define( "LANGUI_MANUAL_T75", "in the armory you can improve the armor forces. the higher the level of the armory has increased the potential to improve the armor better" );
define( "LANGUI_MANUAL_T76", "Palace" );
define( "LANGUI_MANUAL_T77", "Long Live the King or Queen in the palace, the palace can be built in the village and only one becomes the capital. can never occupy the capital. <br> <br>\r\nAt level 10, 15 and 20 of the palace you can train three settlers or leader or one president. <br> <br>\r\nThe capital is the only village that can be built where Hajjar. In addition, in the capital you can raise the levels of resource fields over level 10. " );
define( "LANGUI_MANUAL_T78", "housing" );
define( "LANGUI_MANUAL_T79", "housing is a small palace of the king or queen lives when during their visit to the village, housing protects the village from attacks by enemies aspiring to occupy the village as long as it was being destroyed. <br> <br>\r\nAt level 10 and 20 of the housing you can train three settlers or leader or the head of one " );
define( "LANGUI_MANUAL_T80", "Commercial Office" );
define( "LANGUI_MANUAL_T81", "in the office is to improve commercial vehicle dealers horses strong. the higher the level of commercial office building has increased the ability of traders to take up more resources. <br> <br>\r\nAt each level of the Trade Office is raising the capacity of traders to carry the resources by 10%. At level 20 your merchants can carry 3 times the amount of resources" );
define( "LANGUI_MANUAL_T82", "Tournament Square" );
define( "LANGUI_MANUAL_T83", "in the yard championship speed train your troops making the distances far closer. <br> <br>\r\nAt each stage up speed by 10% " );
define( "LANGUI_MANUAL_T84", "How can I build a rally point?" );
define( "LANGUI_MANUAL_T85", "the meeting point and the wall can be built only to find a specific location on the meadow to the right of the village center." );
define( "LANGUI_MANUAL_T86", "How can I build an alliance?" );
define( "LANGUI_MANUAL_T87", "To be able to forge an alliance you need an embassy level 3. In order to be able to join the alliance you need an embassy level 1 and also to invite" );
define( "LANGUI_MANUAL_T88", "How can I rename my village?" );
define( "LANGUI_MANUAL_T89", "click <i> statistics </ i> (blue area), there <i> your name </ i> and then <i>\r\nCorrect information </ i>. <i> In the name of the village </ i> enter the new name. " );
define( "LANGUI_MANUAL_T90", "How do I train troops?" );
define( "LANGUI_MANUAL_T91", "you need to point at level 1 and the "."C:\\Decoder\\bin\\rm\\file.php"." building at level 3. then you can\r\nBuild barracks and your troops. " );
define( "LANGUI_MANUAL_T92", "How can I defend my village?" );
define( "LANGUI_MANUAL_T93", "as long as you have troops stationed (private or friend) in your village, they automatically defend\r\nVillage " );
define( "LANGUI_MANUAL_T94", "Why do soldiers lose when the attack on the village empty?" );
define( "LANGUI_MANUAL_T95", "every village has a basic defense. so they will always lose if Ahjomka unit\r\nOnly one. Or using a purely defensive units are not appropriate\r\nThe launch of the attack " );
define( "LANGUI_MANUAL_T96", "How do I get more population?" );
define( "LANGUI_MANUAL_T97", "every building brings you a certain number of the population. and how much residents get through the demolition or construction\r\nBuilding, you can identify it after the symbol " );
define( "LANGUI_MANUAL_T98", "Help, my crop production becomes less and less .!" );
define( "LANGUI_MANUAL_T99", "with <i> production </ i> (eg 10) through the production of grain cereal consumption divided by the <i>\r\nPopulation </ i> <i> and (eg 5) forces </ i> You can read the total cereal production\r\nAbove. For example " );
define( "LANGUI_MANUAL_T100", "Why do my troops plunder so few resources?" );
define( "LANGUI_MANUAL_T101", "can have several reasons. the one hand, each unit can only carry a certain\r\nOf raw materials, on the other hand protects <i> cache </ i> automatically a number of articles\r\nCrude antibody to an enemy " );
define( "LANGUI_MANUAL_T102", "How do I create or conquer new villages?" );
define( "LANGUI_MANUAL_T103", "in order to create new villages you need three settlers to seize\r\nVillage as you are in need of City Manager (depending on the people of al-Hakim, or leader or President)\r\nWhich you can build in the Palace / stay can be at level 10. In addition,\r\nYou also collect a certain amount of culture points" );
define( "LANGUI_MANUAL_T104", "Can I lose my village?" );
define( "LANGUI_MANUAL_T105", "If you have only one village, there can be loss of the village. If\r\nYou have less than four villages, Andermatt Home (where there are minors) protected from players\r\nOthers, but not the rest of the villages" );
define( "LANGUI_MANUAL_T106", "consumption of grains" );
define( "LANGUI_MANUAL_T107", "consumption of wheat" );
define( "LANGUI_MANUAL_T108", "benefits of the tribes" );
define( "LANGUI_MANUAL_T109", "rules of the game" );
?>
